# -*- coding: utf-8 -*-
# 好题点睛 批次5（最终批）：好题30~36，共 56 题
# 键格式：{ 文件stem(去.md): { 题号(int): {"gs":公式, "yc":易错, "jq":技巧, "zy":注意} } }
# LaTeX 一律用原始字符串 r"..."，避免转义被 shell/Python 吃掉。

TIPS = {
    "好题30-计算错题": {
        1: {"gs": r"形心 $\bar x=\dfrac{\iint_D x\,\mathrm d\sigma}{\iint_D\mathrm d\sigma}=-\dfrac12 a$，$\bar y=\dfrac{\iint_D y\,\mathrm d\sigma}{\iint_D\mathrm d\sigma}=\dfrac85 a$；交点 $x=-2a$ 与 $x=a$，面积 $\iint_D\mathrm d\sigma=\dfrac92 a^2$。",
            "yc": r"积分上下限易写反：内层 $y$ 从 $\dfrac{x^2}{a}$ 到 $2a-x$；面积公式勿漏 $\mathrm d\sigma$。",
            "jq": r"形心=面积矩÷面积，直接套 $\bar x,\bar y$ 公式，先算面积再算矩，分工清晰。",
            "zy": r"题设 $a>0$，分母面积 $\dfrac92a^2$ 非零；最终坐标含 $a$，注意保留参数。"},
        2: {"gs": r"$D_1=\{(x,y)\mid -y\le x\le 1-y,\ 0\le y\le 1\}$（平行四边形），$I=\int_0^1\mathrm dy\int_{-y}^{1-y}y(x+y)\,\mathrm dx=\int_0^1\tfrac12y\,\mathrm dy=\dfrac14$。",
            "yc": r"$f(x+y)$ 非零区是 $0\le x+y\le 1$，$D_1$ 之外积分为 $0$，勿把积分域扩成全平面。",
            "jq": r"先对 $x$ 后对 $y$ 最顺：$y$ 固定时 $x\in[-y,1-y]$，化为单积分 $\tfrac12\int_0^1y\,\mathrm dy$。",
            "zy": r"分段函数 $f$ 只在 $[0,1]$ 非零，构造积分域即核心。"},
        3: {"gs": r"$V=4\iint_D\sqrt{R^2-x^2-y^2}\,\mathrm d\sigma=4\int_0^{\pi/2}\mathrm d\theta\int_0^{R\cos\theta}\sqrt{R^2-r^2}\,r\,\mathrm dr=\dfrac43R^3\int_0^{\pi/2}(1-\sin^3\theta)\,\mathrm d\theta=\dfrac43\left(\dfrac\pi2-\dfrac23\right)R^3$。",
            "yc": r"只算第一象限再乘 $4$（上下对称+右半 $r=R\cos\theta$），勿漏系数 $4$；$\sin^3\theta$ 在 $[0,\pi/2]$ 积分 $=\dfrac23$。",
            "jq": r"极坐标下 $\sqrt{R^2-r^2}$ 配 $r\,\mathrm dr$ 正好是 $-\frac13(R^2-r^2)^{3/2}$ 的导数，一步到位。",
            "zy": r"圆柱面 $x^2+y^2=Rx$ 即 $r=R\cos\theta$，这是含在圆柱内的球冠（维维安尼体）。"},
        4: {"gs": r"$D$ 为 $(1,0)$ 为圆心、半径 $1$ 的上半圆盘，直线 $x+y-2=0$ 交圆于 $(2,0),(1,1)$；$I=I_1-I_2=1$。其中 $I_2$ 用全区域减 $D_1$：$\iint_D(x+y-2)\,\mathrm d\sigma=\dfrac\pi2\left(1+\dfrac{4}{3\pi}-2\right)=\dfrac23-\dfrac\pi2$。",
            "yc": r"绝对值在直线上、下符号相反，必须分 $D_1,D_2$；直接在 $D_2$ 累次积分繁琐，易出错。",
            "jq": r"利用半圆盘形心 $\left(1,\dfrac{4}{3\pi}\right)$ 与面积 $\dfrac\pi2$ 直接求全区域一次矩，再减 $I_1$ 得 $I_2$。",
            "zy": r"结果恰为 $1$，说明分块后正负恰好抵消余项。"},
        5: {"gs": r"$D=\{(x,y)\mid -2\le x\le 2,\ x^2-4\le y\le 0\}$ 关于 $y$ 轴对称，$\iint_D kx\,\mathrm d\sigma=0$（奇函数），$\iint_D y\,\mathrm d\sigma<0$（$y\le0$ 不恒零）。",
            "yc": r"易误判 $k$ 影响符号；实则 $kx$ 奇函数恒消，$I$ 与 $k$ 无关。",
            "jq": r"对称性消奇+保号性：$y\le0$ 区域上 $\iint y\,\mathrm d\sigma$ 必负，直接选 C。",
            "zy": r"原题解析缺失，按对称性补全；结论 $I<0$ 与 $k$ 无关。"},
        6: {"gs": r"极坐标四分之一圆盘得 $F(t)=\dfrac13t^3-\int_0^t F(r)\,\mathrm dr$；两边对 $t$ 求导 $F'+F=t^2$，解得 $F(t)=t^2-2t+2-2\mathrm e^{-t}$（$t\ge0$）。",
            "yc": r"积分方程求导前须用 $F(0)=0$ 定常数；一阶线性方程积分因子 $\mathrm e^{\int\mathrm dt}=\mathrm e^t$。",
            "jq": r"含 $\sqrt{x^2+y^2}$ 的积分方程先转极坐标化累次，再对上限求导降阶。",
            "zy": r"验证 $F(0)=0$ 得 $C=-2$；$t\to0^+$ 时 $F\to0$ 与定义一致。"},
        7: {"gs": r"外边界 $r=\dfrac1{\sqrt{\sin^4\theta+\cos^4\theta}}$，内边界 $r=\tfrac12$；$I=\dfrac12\int_0^{\pi/2}\dfrac{\sin\theta\cos\theta}{\sin^4\theta+\cos^4\theta}\,\mathrm d\theta-\dfrac18\int_0^{\pi/2}\sin\theta\cos\theta\,\mathrm d\theta$。其中 $\sin^4+\cos^4=\dfrac12(1+\cos^22\theta)$。",
            "yc": r"四条曲线围成域，极径上界是 $\dfrac1{\sqrt{\sin^4\theta+\cos^4\theta}}$ 非 $\tfrac12$；分母公式别写错。",
            "jq": r"令 $t=\cos2\theta$，则 $\dfrac{\sin\theta\cos\theta}{1+\cos^22\theta}\,\mathrm d\theta=-\dfrac12\dfrac{\mathrm d(\cos2\theta)}{1+\cos^22\theta}\to\dfrac\pi4$。",
            "zy": r"结果 $\dfrac1{16}(2\pi-1)$；后半 $\int\sin\theta\cos\theta=\tfrac12$。"},
        8: {"gs": r"摆线 $x=1-\cos t,\ y=t-\sin t$（$0\le t\le2\pi$）。$\iint_D2x\,\mathrm d\sigma=5\pi$，$\iint_Dy\,\mathrm d\sigma=3\pi^2$，故 $I=5\pi+3\pi^2$。",
            "yc": r"参数 $t$ 范围 $0\sim2\pi$ 但 $x=1-\cos t\ge0$；$y$ 与 $x$ 由同一参数关联，勿直接换 $x(y)$。",
            "jq": r"第二部分换元 $u=t-\pi$ 后，奇函数 $u(1+\cos u)^2$、$\sin u(1+\cos u)^2$ 积分为零，只剩 $\pi\int(1+\cos u)^2$。",
            "zy": r"$\sin^6,\cos^4$ 用华里士公式：如 $16\int_0^{\pi/2}\sin^6u\,\mathrm du=5\pi$。"},
        9: {"gs": r"曲线 $2x^2+y^2=2\sqrt{x^2+y^2}$ 即 $r=\dfrac2{1+\cos^2\theta}$；原式 $=2\int_0^{\pi/2}\dfrac{\mathrm d(\tan\theta)}{\tan^2\theta+2}=\sqrt2\arctan\dfrac{\tan\theta}{\sqrt2}\Big|_0^{\pi/2}=\dfrac{\sqrt2}{2}\pi$。",
            "yc": r"根号代入后 $\sqrt{1-\dfrac{4\cos^2\theta}{(1+\cos^2\theta)^2}}=\dfrac{1-\cos^2\theta}{1+\cos^2\theta}$（平方开根号），别漏配方。",
            "jq": r"极坐标+万能代换 $\tan\theta$：被积化为 $\dfrac{2}{1+\cos^2\theta}=\dfrac{2\sec^2\theta}{\tan^2\theta+2}$。",
            "zy": r"区域仅第一象限；$\sec^2\theta\,\mathrm d\theta=\mathrm d(\tan\theta)$ 直接凑微分。"},
        10: {"gs": r"$k=\dfrac1{\mathrm e^x-1}-\dfrac1x=f(x)$，$f'(x)=\dfrac{(e^x-1)^2-x^2e^x}{x^2(e^x-1)^2}>0$；$f(0^+)=-\dfrac12$，$f(+\infty)=0$，故 $k\in\left(-\dfrac12,0\right)$。",
            "yc": r"由 $\mathrm e^x-1>x$ 知 $f(x)<0$，上限是 $0$ 而非正；下限 $-\tfrac12$ 由洛必达得。",
            "jq": r"单调+两端极限夹出值域：$g'>0$ 用泰勒 $2\mathrm e^x-2-2x-x^2=2\sum_{n\ge3}\tfrac{x^n}{n!}>0$。",
            "zy": r"两曲线在第一象限相交$\Leftrightarrow$存在 $x>0$ 使 $k=f(x)$；$f$ 单增则值域即范围。"},
        11: {"gs": r"$D_1:0\le r\le2,0\le\theta\le\tfrac\pi2$；$D_2:0\le r\le\dfrac2{\sin\theta-\cos\theta},\tfrac\pi2\le\theta\le\pi$。$\dfrac{(x-y)^2}{x^2+y^2}=(\cos\theta-\sin\theta)^2$；$I=(\pi-2)+\pi=2\pi-2$。",
            "yc": r"直线 $y=x+2$ 极线 $r=\dfrac2{\sin\theta-\cos\theta}$，注意 $\theta\in[\pi/2,\pi]$ 时 $\sin\theta-\cos\theta>0$。",
            "jq": r"$D_2$ 中被积 $(\cos\theta-\sin\theta)^2\cdot\tfrac12\left[\tfrac2{\sin\theta-\cos\theta}\right]^2=2$ 为常数，直接得 $\pi$。",
            "zy": r"$D_1$ 部分 $\int_0^{\pi/2}(1-\sin2\theta)\,\mathrm d\theta=\tfrac\pi2-1$，乘半径积分 $\int_0^2r\,\mathrm dr=2$。"},
        12: {"gs": r"驻点 $(1,1),(2,1)$；$(1,1)$：$A=-6,B=0,C=-72$，$AC-B^2>0,A<0$ 极大值点；$(2,1)$：$AC-B^2<0$ 非极值点。唯一极值点 $(1,1)$。",
            "yc": r"二元极值充分条件 $AC-B^2>0$ 且 $A<0$ 才极大值；$(2,1)$ 处 $AC-B^2<0$ 不是极值，勿漏判。",
            "jq": r"逐点算二阶偏导 $f_{xx}=12x-18,f_{xy}=0,f_{yy}=-72y^2$，套判别式。",
            "zy": r"问的是极值点（坐标），不是极值；答案填 $(1,1)$。"},
        13: {"gs": r"$\int_0^2y(x)\,\mathrm dx=3\ln(1+\sqrt2)-\sqrt2+1$。$x=1/t$（$t>1$）分部积分，再加 $t\in[0,1]$ 段。",
            "yc": r"$t>1$ 时 $x=1/t\in(0,1)$，积分方向反转出负号；$\lim_{t\to\infty}\tfrac{\ln(t+\sqrt{1+t^2})}{t}=0$。",
            "jq": r"分段：$t=\tan u$ 算 $\int_1^\infty\tfrac{\mathrm dt}{t\sqrt{1+t^2}}=\ln(1+\sqrt2)$；第二段分部得 $\ln(1+\sqrt2)-(\sqrt2-1)$。",
            "zy": r"两段均含 $\ln(1+\sqrt2)$，合并为 $3\ln(1+\sqrt2)-\sqrt2+1$。"},
        14: {"gs": r"有理化：$\dfrac{x^2+x+1-(ax+b)^2}{\sqrt{x^2+x+1}-(ax+b)}=0$，分母为 $x\to-\infty$ 一阶无穷大，须 $1-a^2=0,\ 1-2ab=0$，结合 $a>0$ 得 $a=1,b=\tfrac12$。",
            "yc": r"$x\to-\infty$ 须 $a>0$（否则两项同号发散）；只消二次项系数不够，一次项也要消，得 $b=\tfrac12$。",
            "jq": r"有理化后分子按 $x$ 降幂，分母一阶，要求分子 $x^2,x$ 系数均为 $0$。",
            "zy": r"验证：$\sqrt{x^2+x+1}=-x-\tfrac12+o(1)$（$x\to-\infty$），加 $x+\tfrac12\to0$。"},
        15: {"gs": r"$S_n=\int_0^{n\pi}x\cos^2x\,\mathrm dx=\tfrac12\int_0^{n\pi}x(1+\cos2x)\,\mathrm dx=\tfrac14n^2\pi^2+\tfrac14[x\sin2x]_0^{n\pi}-\tfrac14\int_0^{n\pi}\sin2x\,\mathrm dx=\tfrac14n^2\pi^2$；极限 $\tfrac14\pi^2$。",
            "yc": r"$\int_0^{n\pi}\sin2x\,\mathrm dx=0$（整周期）；分部后边界项 $x\sin2x|_{0}^{n\pi}=0$。",
            "jq": r"$\cos^2x=\tfrac12(1+\cos2x)$，把 $x\cos2x$ 分部，振荡项积分为零。",
            "zy": r"$y=x\cos^2x\ge0$（$x\ge0$），面积即积分；极限 $\tfrac{n^2\pi^2}{4(n+1)^2}\to\tfrac{\pi^2}4$"},
        16: {"gs": r"由 $\lim_{x\to0}\tfrac{1-f(x)}x=1$ 得 $f(0)=1,f'(0)=-1$；由函数方程 $f'(x)=f(x)f'(0)=-f(x)$，故 $f(x)=\mathrm e^{-x}$。$F(x)=|x|\mathrm e^{-x}$：$F(0)=0$ 极小，$F(1)=\mathrm e^{-1}$ 极大。",
            "yc": r"$F$ 在 $x=0$ 不可导（左右导数 $\mp1$），极值点不能只看导数为零；$x=1$ 处 $F'=0$。",
            "jq": r"指数函数特征方程 $f(x+y)=f(x)f(y)$ 配导数定义得 $f'=-f$，直接解。",
            "zy": r"分段讨论 $x\le0,x>0$ 求导：$F'(x)=\mathrm e^{-x}(x-1)$（$x<0$）、$\mathrm e^{-x}(1-x)$（$x>0$）。"},
        17: {"gs": r"由对称性 $\bar y=0$；$|\theta|\le\tfrac\pi2$ 边界圆 $r=1$，$\tfrac\pi2\le|\theta|\le\pi$ 边界心形线 $r=1+\cos\theta$。$\bar x=\dfrac{15\pi-32}{30\pi-48}$。",
            "yc": r"公共区域不是整圆也不是整心形线，按 $|\theta|$ 分段取边界；面积 $= \tfrac\pi2+\int_{\pi/2}^\pi(1+\cos\theta)^2\,\mathrm d\theta$。",
            "jq": r"$\bar y=0$ 由对称性直接得；$\bar x$ 分两段积分再除以总面积。",
            "zy": r"核验：$\int_{\pi/2}^\pi\cos\theta(1+\cos\theta)^3\,\mathrm d\theta=\tfrac{15\pi}{16}-3$。"},
    },
    "好题31-矩阵问题": {
        1: {"gs": r"奇数阶非零反对称阵 $\mathrm r(A)=2$（$|A|=0$ 且秩为偶），故 $Ax=0$ 有非零解。$\mathrm r(A(B-E))=1<\mathrm r(A)\Rightarrow B-E$ 不可逆，$|B-E|=0\Rightarrow a=2$；$B$ 可逆故 $Bx=0$ 仅零解，选 B。",
            "yc": r"反对称矩阵秩必为偶数、奇数阶行列式必为 $0$；误以为 $a$ 任意使 $\mathrm r(B-E)$ 可逆。",
            "jq": r"$\mathrm r(AB-A)=1<\mathrm r(A)$ 推出 $B-E$ 不可逆（列线性相关）；再算 $|B|$ 判定 $B$ 可逆。",
            "zy": r"结论：$Ax=0$ 有非零解、$Bx=0$ 仅零解，选 (B)。"},
        2: {"gs": r"公共解 $\alpha$ 满足 $k_1\xi_1+k_2\xi_2=l_1\eta_1+l_2\eta_2$，即 $(\xi_1,\xi_2,-\eta_1,-\eta_2)\begin{pmatrix}k_1\\k_2\\l_1\\l_2\end{pmatrix}=0$；行化简得 $(1,0,0,2;0,1,0,1;0,0,1,1)$，故 $\alpha=k(-1,-1,2,-1)^{\mathrm T}$。",
            "yc": r"拼接系数矩阵时 $-\eta_1,-\eta_2$ 带负号；行化简后令自由变量得 $k_1=-2k$ 等。",
            "jq": r"把两个基础解系表示相等，拼成 $4\times4$ 齐次方程组，行最简形直接读通解。",
            "zy": r"验证 $-2k\xi_1-k\xi_2=k(-1,-1,2,-1)^{\mathrm T}$ 与 $-k\eta_1+k\eta_2$ 一致。"},
        3: {"gs": r"$\begin{pmatrix}A&E\\O&B\end{pmatrix}^*=\begin{pmatrix}|B|A^*&-A^*B^*\\O&|A|B^*\end{pmatrix}$，选 D。由 $M^*=|M|M^{-1}$、$|M|=|A||B|$。",
            "yc": r"交叉项易错写为 $-B^*A^*$ 或顺序反；正确是 $-A^*B^*$（左上块 $|B|A^*$）。",
            "jq": r"两法：①求逆 $M^{-1}=\begin{pmatrix}A^{-1}&-A^{-1}B^{-1}\\O&B^{-1}\end{pmatrix}$ 再乘 $|A||B|$；②用 $MM^*=|M|E$ 排除选项。",
            "zy": r"$|A|A^{-1}=A^*$，$|B|B^{-1}=B^*$，故 $|A||B|A^{-1}B^{-1}=A^*B^*$。"},
    },
    "好题32-求相似正交转置矩阵问题": {
        1: {"gs": r"$|\lambda E-A|=(\lambda-a+1)^2(\lambda-a-2)$；$\mathrm r[A-(a-1)E]=2$，二重特征值只 $1$ 个无关特征向量，故 $A$ 不可对角化。由 $AP=PB$ 得 $P=\begin{pmatrix}2k_1&2k_1+2k_2&-k_3\\-k_1&-3k_1-k_2&-k_3\\k_1&k_2&k_3\end{pmatrix}$，$|P|=-9k_1^2k_3\ne0$。",
            "yc": r"二重特征值 $\mathrm r(A-\lambda E)=2$ 说明几何重数 $1<2$，不能对角化；勿漏判存在性。",
            "jq": r"解 $AP=PB$ 逐列：$Ax_1=\lambda_1x_1$（特征向量），$Ax_2=x_1+\lambda_1x_2$（广义），联立增广阵。",
            "zy": r"$k_1k_3\ne0$，$k_2$ 任意；$x_3=(-1,-1,1)^{\mathrm T}$ 为 $\lambda=a+2$ 特征向量。"},
        2: {"gs": r"选 C：$B=A^{-1}$ 或 $B=A-E$，与 $A$ 同特征向量，可用同一正交阵对角化。C 中 $AB=BA=E$。",
            "yc": r"误以为任意一对都可用同 $P$；只有可交换且 $A$ 有互异特征值时才共享特征向量。",
            "jq": r"实对称阵若 $AB=BA$ 且 $A$ 特征值互异，则 $B$ 的特征向量即 $A$ 的；C 中 $B=A^{-1}$ 显然同特征向量。",
            "zy": r"也可用 $f(A),A^{-1},A^*$ 与 $A$ 同对角化阵；C 选项 $|A|=-1$，$A^{-1}=B$。"},
        3: {"gs": r"由 $AB=A-B$ 得 $(A+E)(E-B)=E$，故 $B=E-(A+E)^{-1}$。$A$ 特征值 $-3,0,3\Rightarrow B$ 特征值 $\tfrac32,0,\tfrac34$，特征向量同 $\xi_1,\xi_2,\xi_3$。令 $P=(\xi_1,\xi_2,\xi_3)$，则 $P^{-1}(AB)P=P^{-1}AP-P^{-1}BP=\operatorname{diag}(-\tfrac92,0,\tfrac94)$。",
            "yc": r"$AB$ 的特征值 $=\lambda_A-\lambda_B$ 而非乘积；$\tfrac94=3-\tfrac34$ 等逐项相减。",
            "jq": r"先求 $A$ 的特征向量（已标准化），再利用 $(A+E)(E-B)=E$ 推出 $B$ 特征值 $1-\tfrac1{\lambda+1}$。",
            "zy": r"对角阵两矩阵相减：$P^{-1}(A-B)P=\Lambda_A-\Lambda_B$。"},
    },
    "好题33-线性无关证明": {
        1: {"gs": r"由 $A\xi_1=0$，且 $A\xi_2=\xi_1$、$A^2\xi_3=\xi_1$。设 $a\xi_1+b\xi_2+c\xi_3=0$，左乘 $A^2$ 得 $cA^2\xi_3=c\xi_1=0\Rightarrow c=0$；再左乘 $A$ 得 $bA\xi_2=b\xi_1=0\Rightarrow b=0$；从而 $a=0$。故无关。",
            "yc": r"不能直接证 $A\xi_2=\xi_1$ 推出 $\xi_2$ 与 $\xi_1$ 无关；须用算子幂逐步消去未知数。",
            "jq": r"左乘 $A^2$ 消去前两项（因 $A^2\xi_1=A\xi_1=0,A^2\xi_2=A\xi_1=0$），只剩 $c\xi_1$；再乘 $A$ 消 $b$。",
            "zy": r"构造链 $A\xi_1=0\Rightarrow A^2\xi_2=A\xi_1=0\Rightarrow A^3\xi_3=0$；利用算子幂分层消去系数。"},
    },
    "好题34-线性方程组问题": {
        1: {"gs": r"设 $C=\begin{pmatrix}x_1&x_2\\x_3&x_4\end{pmatrix}$，化方程组 $Px=\beta$；行化简得 $\mathrm r(P,\beta)=\mathrm r(P)$ 当且仅当 $a+1=0,b=0$，即 $a=-1,b=0$。此时 $C=\begin{pmatrix}k_1+k_2+1&-k_2\\k_2&k_1\end{pmatrix}$。",
            "yc": r"矩阵方程展开易错（尤其 $AC-CA$ 的非对角项）；法二用 $\operatorname{tr}(AC-CA)=0\Rightarrow b=0$ 更快。",
            "jq": r"代入 $x_2=ax_3$ 得 $-a(x_1-x_3-x_4)=1$，与第三式比较直接得 $a=-1$。",
            "zy": r"有解条件看增广阵秩相等；特解 $(1,0,0,0)^{\mathrm T}$，基础解系 $(1,0,0,1)^{\mathrm T},(1,-1,1,0)^{\mathrm T}$。"},
        2: {"gs": r"$\alpha_1,\alpha_2,\alpha_3$ 与 $\alpha_1,\alpha_2,\alpha_4$ 等价 $\Leftrightarrow\mathrm r(\alpha_1,\alpha_2,\alpha_3)=\mathrm r(\alpha_1,\alpha_2,\alpha_4)=\mathrm r(\alpha_1,\alpha_2,\alpha_3,\alpha_4)$。$|\alpha_1\alpha_2\alpha_3|=(1-\lambda)^2(\lambda+2)$，$|\alpha_1\alpha_2\alpha_4|=(1-\lambda)^2(1+\lambda)^2$，故 $\lambda\ne-2,-1$，选 C。",
            "yc": r"$\lambda=1$ 时四向量全相等仍等价，已含在 $\lambda\ne-2,-1$ 内；勿漏 $\lambda=1$ 情形。",
            "jq": r"等价当且仅当秩相等且互相包含；算两个 $3$ 阶行列式非零区间取交。",
            "zy": r"$\lambda=-2$ 或 $-1$ 时其中一个行列式为 $0$，秩不等，排除。"},
        3: {"gs": r"$A\ne O$ 且 $A^2=O\Rightarrow\mathrm r(A)+\mathrm r(A)\le3\Rightarrow\mathrm r(A)=1$。$A^{\mathrm T}Ax=A^{\mathrm T}b$ 必有解，$\mathrm r(A^{\mathrm T}A)=\mathrm r(A)=1$，线性无关解向量个数 $=3-\mathrm r+1=3$，选 C。",
            "yc": r"非齐次解的线性无关个数 $=n-\mathrm r+1$（含 $1$ 特解 $+ (n-\mathrm r)$ 基础解系），易漏 $+1$。",
            "jq": r"$\mathrm r(A^TA)=\mathrm r(A)$ 恒成立；$A^2=O$ 用秩不等式夹出 $\mathrm r(A)=1$。",
            "zy": r"$(A^{\mathrm T}A,A^{\mathrm T}b)=A^{\mathrm T}(A,b)$，故必有解；通解含 $2$ 个齐次基 $+1$ 特解 $=3$ 无关解。"},
        4: {"gs": r"$\mathrm r(\alpha_1,\alpha_2,\alpha_3)=2$（相关且任意两无关）。取 $1,2,4$ 行：$\begin{vmatrix}a&1&1\\1&1&a\\1&a&1\end{vmatrix}=-(a+2)(a-1)^2=0\Rightarrow a=-2$ 或 $1$；$a=1$ 时 $\alpha_1=\alpha_3$ 舍，故 $a=-2$；再取 $1,2,3$ 行得 $b=2$，$ab=-4$。",
            "yc": r"$a=1$ 使 $\alpha_1=\alpha_3$ 违反两两无关，必须舍去；只看一个子式会漏此判据。",
            "jq": r"秩为 $2$ 则任意 $3$ 阶子式为 $0$，取两个不同子式联立解 $a,b$。",
            "zy": r"验证：$a=-2,b=2$ 时 $\alpha_2=-\alpha_1-\alpha_3$，且任意两不成比例。"},
        5: {"gs": r"行和为零 $\Rightarrow|A|=0$ 且 $A(1,1,1,1)^{\mathrm T}=0$，$AA^*=O$。若 $\mathrm r(A)=3$ 则 $\mathrm r(A^*)=1$，$A^*$ 列均为 $Ax=0$ 解 $\Rightarrow A_{2j}$ 全相等、$M_{21}+M_{22}+M_{23}+M_{24}=0$；①④必立，选 B。",
            "yc": r"$\mathrm r(A)<3$ 时 $A^*=O$ 四项全 $0$ 也成立；$\mathrm r(A)=3$ 时②$\sum A_{2j}=4c$、③$M_{21}=M_{22}$ 要求 $c=0$ 不必然。",
            "jq": r"利用 $A^*$ 列空间 $\subset\ker A$，且 $\ker A$ 由 $(1,1,1,1)^{\mathrm T}$ 张成（当 $\mathrm r(A)=3$）。",
            "zy": r"$A_{2j}=(-1)^{2+j}M_{2j}$，故 $M_{21}+M_{22}+M_{23}+M_{24}=-c+c-c+c=0$ 恒成立。"},
    },
    "好题35-特征与二次型问题": {
        1: {"gs": r"$f=x^{\mathrm T}(2\alpha\alpha^{\mathrm T}+\beta\beta^{\mathrm T})x$，$A=2\alpha\alpha^{\mathrm T}+\beta\beta^{\mathrm T}$ 对称。$A\alpha=2\alpha,A\beta=\beta$；$\mathrm r(\alpha\alpha^{\mathrm T})=\mathrm r(\beta\beta^{\mathrm T})=1\Rightarrow\mathrm r(A)\le2$，故 $0$ 也是特征值。标准形 $2y_1^2+y_2^2$。",
            "yc": r"$\alpha,\beta$ 须正交单位，否则 $A\alpha\ne2\alpha$；结论 $0$ 特征值由秩 $\le2<3$ 推出。",
            "jq": r"秩 $1$ 矩阵 $\alpha\alpha^{\mathrm T}$ 的特征值：$1$（对应 $\alpha$）、$0$（重 $n-1$）。",
            "zy": r"正交变换下标准形系数即特征值 $2,1,0$。"},
        2: {"gs": r"令 $y_1=x_1+x_2+2x_3,\ y_2=x_2+ax_3,\ y_3=x_3$ 可逆 $\Rightarrow f=y_1y_2$；再令 $z_1=y_1+y_2,z_2=y_1-y_2$ 得 $f=z_1^2-z_2^2$，故 $\mathrm r(f)=2$，选 B。",
            "yc": r"$|A|=0$ 但有 $2$ 阶非零子式 $\begin{vmatrix}0&1/2\\1/2&1\end{vmatrix}\ne0$，秩恰为 $2$ 非 $3$。",
            "jq": r"两法：①配可逆变换化 $y_1y_2$ 再平方差；②写对称矩阵看秩。",
            "zy": r"正、负惯性指数均为 $1$，秩 $2$ 与 $a$ 无关，选 (B)。"},
        3: {"gs": r"行和为零 $\Rightarrow A(1,1,1)^{\mathrm T}=0$，故 $\lambda_1=0$ 对应 $\xi_1=(1,1,1)^{\mathrm T}$。$\operatorname{tr}(A)=2$ 且重特征值 $\Rightarrow\lambda_2=\lambda_3=1$；对应特征向量满足 $x_1+x_2+x_3=0$，取 $\xi_2=(-1,1,0)^{\mathrm T},\xi_3=(1,1,-2)^{\mathrm T}$。",
            "yc": r"行和为零即 $(1,1,1)^{\mathrm T}$ 是 $\lambda=0$ 特征向量；重特征值 $+ \operatorname{tr}=2$ 推出两个 $1$。",
            "jq": r"实对称不同特征值特征向量正交，故 $\lambda=1$ 的特征向量落在 $x_1+x_2+x_3=0$ 平面内。",
            "zy": r"$\lambda=1$ 的全部特征向量为 $k_2\xi_2+k_3\xi_3$（$k_2,k_3$ 不全为零）。"},
        4: {"gs": r"$A(B-E)=2(B-E)\Rightarrow B-E$ 的非零列是 $A$ 的 $\lambda=2$ 特征向量。$B=\alpha\alpha^{\mathrm T}$ 特征值 $1,0,0\Rightarrow B-E$ 特征值 $0,-1,-1$，$\mathrm r(B-E)=2$。$A$ 不可逆 $\Rightarrow\lambda=0$。故特征值 $2,2,0$，选 D。",
            "yc": r"$\lambda=2$ 是二重（因 $\mathrm r(B-E)=2$ 至少二维特征空间），不是三重也不是单根。",
            "jq": r"由算子方程 $A(B-E)=2(B-E)$ 直接读特征向量；秩 $1$ 矩阵 $B$ 特征值 $1,0,0$。",
            "zy": r"$A$ 不可逆保证 $\lambda=0$ 必出现，三者即 $2,2,0$。"},
        5: {"gs": r"行变换 $E(1(2))E(3,1(2))\,A\,\cdots=C$，即 $P^{\mathrm T}AP=C$，$A$ 与 $C$ 合同 $\Rightarrow A^*$ 与 $C^*$ 合同。$|C|=16|A|\Rightarrow|C^*|=256|A|^2\ne|A|^2$，不相似，选 A。",
            "yc": r"合同保正负惯性指数，但不保行列式；$|C^*|\ne|A^*|$ 故不相似。",
            "jq": r"行、列初等变换分别对应左乘 $E$、右乘 $E^{\mathrm T}$；组合得 $P^{\mathrm T}AP$。",
            "zy": r"区分：合同 $\Leftrightarrow$ 同惯性指数；相似 $\Leftrightarrow$ 同特征值（含重数）同行列式。"},
        6: {"gs": r"$A(\alpha+\beta)=2(\alpha+\beta)$，$A(\alpha-\beta)=-2(\alpha-\beta)$；$\mathrm r(AB)<\mathrm r(B)\Rightarrow A$ 不可逆 $\Rightarrow\lambda_3=0$。单位化得 $Q$，标准形 $2y_1^2-2y_2^2$。$\gamma=\alpha_1-2\alpha_2+\alpha_3\Rightarrow A^{2024}\gamma=2^{2024}(2,-1,3)^{\mathrm T}$。",
            "yc": r"高次幂用特征分解：只 $\lambda_1=2,\lambda_2=-2$ 非零项，$\lambda_3=0$ 项消失；$(-2)^{2024}=2^{2024}$。",
            "jq": r"把 $\gamma$ 表成特征向量线性组合 $\gamma=\alpha_1-2\alpha_2+\alpha_3$，再逐项乘 $\lambda^{2024}$。",
            "zy": r"验证 $\alpha_1-2\alpha_2+\alpha_3=(1,0,4)^{\mathrm T}=\gamma$。"},
        7: {"gs": r"$A$ 可逆且 $A^2+2A=O\Rightarrow A=-2E$（特征值全 $-2$，$|A|=-8$）。代入 $2A^{-1}B=A^*+B$ 得 $-B=4E+B\Rightarrow B=-2E$，$|B|=-8$。",
            "yc": r"原书法一符号易错写作 $|B|=8$，应以法二/法三 $B=-2E$ 为准；答案是 $-8$ 非 $8$。",
            "jq": r"由 $A^2+2A=O$ 且 $A$ 可逆直接得 $A=-2E$，再代原式解 $B$。",
            "zy": r"$A^*=|A|A^{-1}=(-8)(-\tfrac12E)=4E$；$2A^{-1}B=A^*+B\Rightarrow -B=4E+B$。"},
        8: {"gs": r"(Ⅰ)$|\lambda E-A^{\mathrm T}|=|(\lambda E-A)^{\mathrm T}|=|\lambda E-A|$，多项式同。不同特征值特征向量正交：$(\lambda_1-\lambda_2)\alpha_2^{\mathrm T}\alpha_1=0$。(Ⅱ)$A=\begin{pmatrix}1&3\\1&-1\end{pmatrix}$，特征值 $2,-2$；$P=P_1P_2^{-1}=\tfrac12\begin{pmatrix}5&1\\1&1\end{pmatrix}$ 使 $P^{-1}AP=A^{\mathrm T}$。",
            "yc": r"(Ⅱ)须 $P=P_1P_2^{-1}$ 使 $P^{-1}AP=\Lambda=P_2^{-1}A^{\mathrm T}P_2$；直接拼错序。",
            "jq": r"转置特征向量用 $A^{\mathrm T}$ 的；正交性证明靠 $\alpha_2^{\mathrm T}A\alpha_1$ 两种写法相等。",
            "zy": r"核验 $AP=PA^{\mathrm T}$：两边均等于 $\tfrac12\begin{pmatrix}8&4\\4&0\end{pmatrix}$。"},
        9: {"gs": r"$P=(e_1+e_2,e_2,e_3)=Q\begin{pmatrix}1&0&0\\1&1&0\\0&0&1\end{pmatrix}=QC$。$P^{\mathrm T}AP=C^{\mathrm T}\Lambda C=\begin{pmatrix}2&1&0\\1&1&0\\0&0&3\end{pmatrix}$，选 B。",
            "yc": r"$(QC)^{\mathrm T}=C^{\mathrm T}Q^{\mathrm T}$ 不是 $Q^{\mathrm T}C$；穿脱原则别漏转置。",
            "jq": r"正交阵 $Q^{\mathrm T}=Q^{-1}$，$P^{\mathrm T}AP=C^{\mathrm T}(Q^{\mathrm T}AQ)C=C^{\mathrm T}\Lambda C$。",
            "zy": r"$C=\begin{pmatrix}1&0&0\\1&1&0\\0&0&1\end{pmatrix}$，其转置乘 $\Lambda$ 乘自身出交叉项 $1$。"},
        10: {"gs": r"由 $A^2=2E$，$|A|>0\Rightarrow|A|=2$，$AA^*=2E$。左乘 $\begin{pmatrix}E&O\\A&E\end{pmatrix}$ 化块为 $\begin{pmatrix}A^*&A^*-E\\B^*+E&O\end{pmatrix}$，行列式 $=(-1)^4|A^*-E||B^*+E|$。$A\sim B\Rightarrow A^*\sim B^*$，值为 $\dfrac{|4E-A^2|}{4}=\dfrac{|2E|}{4}=1$。",
            "yc": r"分块行列式公式：左下块化简 $AA^*+B^*-E=B^*+E$；右下块 $A(A^*-E)+A-2E=O$。",
            "jq": r"相似保 $A^*\sim B^*$，把 $|A^*-E||B^*+E|$ 化为 $|A^*-E||A^*+E|=|(2A^{-1}-E)(2A^{-1}+E)|$。",
            "zy": r"$|A|=2$ 故 $A^*=2A^{-1}$；最终 $\dfrac{|4E-A^2|}{|A|^2}=\dfrac{|2E|}{4}=1$。"},
        11: {"gs": r"$f=0\Leftrightarrow$ 三式联立。系数阵行化简得 $a-2$：当 $a\ne2$ 仅零解（正定，规范形 $y_1^2+y_2^2+y_3^2$）；当 $a=2$ 解 $k(-2,-1,1)^{\mathrm T}$，$B=\begin{pmatrix}2&-1&3\\-1&2&0\\3&0&6\end{pmatrix}$，$|B|=0$ 但 $2$ 阶非零，规范形 $z_1^2+z_2^2$。",
            "yc": r"$f\ge0$ 故负惯性指数必 $0$；$a=2$ 时秩 $=2$（非 $3$），规范形只有两项。",
            "jq": r"平方和非负 $\Rightarrow$ 正定或半正定；秩由 $2$ 阶子式非零+行列式 $0$ 定为 $2$。",
            "zy": r"规范形看 $(p,q)$：$a\ne2$ 为 $(3,0)$；$a=2$ 为 $(2,0)$。"},
        12: {"gs": r"$\alpha_1+\alpha_2+\alpha_3=(1,1,1)^{\mathrm T}\Rightarrow\lambda=1$ 对应 $(1,1,1)^{\mathrm T}$。代入 $A^3+(a^5-1)A^2+2a^3A+aE=O$ 得 $a=0\Rightarrow A^3-A^2=O$，特征值只 $0,1$；$\operatorname{tr}(A)=1\Rightarrow$ 特征值 $0,0,1$。①④正确，选 C。",
            "yc": r"③不正：实对称合同看惯性指数，$A$ 正惯性指数 $1$，$\operatorname{diag}(1,2,0)$ 为 $2$，不合同。",
            "jq": r"不同特征值特征向量正交 $\Rightarrow Ax=0$ 的解满足 $x_1+x_2+x_3=0$，$(1,1,-2)^{\mathrm T}$ 符合。",
            "zy": r"正确个数 $3$（①②④）；③错因惯性指数不同。"},
        13: {"gs": r"(Ⅰ)$\lambda^2=-1$ 无实特征值 $\Rightarrow A^{\mathrm T}\ne A$。(Ⅱ)设 $k_1\alpha+k_2A\alpha=0$，左乘 $A$ 得 $k_1A\alpha-k_2\alpha=0$，联立 $\Rightarrow(k_1^2+k_2^2)\alpha=0\Rightarrow k_1=k_2=0$，$P$ 可逆。(Ⅲ)$AP=(A\alpha,-\alpha)=PB$，$B=\begin{pmatrix}0&-1\\1&0\end{pmatrix}$，故相似。",
            "yc": r"(Ⅲ)须先证 $P$ 可逆才能写 $P^{-1}AP=B$；$A^2=-E$ 直接给 $A(A\alpha)=-\alpha$。",
            "jq": r"左乘 $A$ 利用 $A^2=-E$ 消去，得到与原式联立的齐次组，证线性无关。",
            "zy": r"旋转阵 $B$ 正是平面上 $90^\circ$ 旋转，特征值 $\pm i$ 与 $A$ 一致。"},
        14: {"gs": r"选 B（充分不必要）。$A$ 两不等特征值 $\Rightarrow$ 两无关特征向量；由 $AB=BA$ 推 $B\alpha_i$ 亦为 $A$ 的特征向量，故 $B$ 有两无关特征向量可对角化。反例 $A=B=E$ 必要不成立。",
            "yc": r"充分性靠 $AB=BA$ 保特征向量；必要性反例取幂等/单位阵即可。",
            "jq": r"可对角化 $\Leftrightarrow n$ 个线性无关特征向量；交换性使 $B$ 与 $A$ 共享特征向量。",
            "zy": r"$A=B=E$ 时 $B$ 对角但 $A$ 无两不等特征值，故非必要。"},
        15: {"gs": r"(Ⅰ)$A^{-1}$ 特征向量即 $A$ 的：设 $A\alpha=\lambda\alpha$ 得 $\lambda=2,a+b=0$，代入 $|A|=24$ 得 $a=2,b=-2$。(Ⅱ)$A$ 特征值 $2,2,6$，$P=\begin{pmatrix}1&1&1\\0&-1&-2\\1&0&3\end{pmatrix}$。(Ⅲ)$Q=PP^{\mathrm T}=\begin{pmatrix}3&-3&4\\-3&5&-6\\4&-6&10\end{pmatrix}$ 使 $Q^{-1}AQ=A^{\mathrm T}$。",
            "yc": r"$A^{-1}$ 与 $A$ 同特征向量（仅倒数），勿误当不同；$\operatorname{tr}(A)=10,|A|=24,\lambda=2$ 定另两特征值为 $2,6$。",
            "jq": r"由 $(P^{-1}AP)^{\mathrm T}=\Lambda$ 推 $A^{\mathrm T}=(PP^{\mathrm T})^{-1}A(PP^{\mathrm T})$，令 $Q=PP^{\mathrm T}$。",
            "zy": r"验证 $Ap_i=\lambda p_i$ 逐列成立；$Q$ 对称可逆。"},
        16: {"gs": r"$A$ 为 $2\times3$，则 $AA^{\mathrm T}$ 为 $2$ 阶、$A^{\mathrm T}A$ 为 $3$ 阶。由 $|A^{\mathrm T}A-2E|=0$ 知 $2$ 是 $A^{\mathrm T}A$ 特征值，且也是 $AA^{\mathrm T}$ 特征值；$|AA^{\mathrm T}|=2$ 得另一特征值 $1$；同理 $1$ 也是 $A^{\mathrm T}A$ 特征值。$\mathrm r(AA^{\mathrm T})=2\Rightarrow0$ 是 $A^{\mathrm T}A$ 特征值。故 $|A^{\mathrm T}A+2E|=4\cdot3\cdot2=24$，选 D。",
            "yc": r"非方阵特征值沿 $Ax\ne0$ 两侧传递；$\mathrm r(AA^{\mathrm T})=2<3$ 故 $A^{\mathrm T}A$ 必含 $0$ 特征值。",
            "jq": r"若 $A^{\mathrm T}Ax=2x$（$x\ne0$）则 $AA^{\mathrm T}(Ax)=2(Ax)$，特征值 $2$ 双向传。",
            "zy": r"$A^{\mathrm T}A$ 特征值 $\{2,1,0\}$，加 $2E$ 后 $\{4,3,2\}$，乘积 $24$"},
        17: {"gs": r"选 B（2 个）。①$|A||B|=|A|^2|P|^2\ge0$ 对；②合同 $\Rightarrow\mathrm r(B)=\mathrm r(A)$ 等价，对；③反例 $A=\operatorname{diag}(1,0),B=\begin{pmatrix}1&1\\1&1\end{pmatrix}$ 合同但行向量组不等价；④反例 $A=\begin{pmatrix}1&1\\0&1\end{pmatrix}$ 不可对角化但合同的 $B$ 可对角化。",
            "yc": r"合同只保秩与惯性指数，不保行向量组等价、不保可对角化。",
            "jq": r"举反例：③取正惯性指数相同的两个实对称阵；④取 Jordan 块配对角阵。",
            "zy": r"正确命题仅 ①②，共 2 个，选 (B)。"},
        18: {"gs": r"作合同变换 $\begin{pmatrix}E&0\\-\alpha^{\mathrm T}&1\end{pmatrix}^{\mathrm T}\begin{pmatrix}A+\alpha\alpha^{\mathrm T}&\alpha\\\alpha^{\mathrm T}&1\end{pmatrix}\begin{pmatrix}E&0\\-\alpha^{\mathrm T}&1\end{pmatrix}=\begin{pmatrix}A&0\\0&1\end{pmatrix}$；$|\lambda E-B|=(\lambda-1)(\lambda^2-2)$，正惯性指数 $p=2$、负 $q=1$，规范形 $y_1^2+y_2^2-y_3^2$，选 C。",
            "yc": r"分块消 $\alpha$ 列成零须左、右同乘配套初等阵；惯性指数由 $B$ 的特征值 $(1,\pm\sqrt2)$ 定。",
            "jq": r"分块合同变换把右下块化为常数 $1$、左上块化为 $A$，直接读惯性指数。",
            "zy": r"也可取特例 $\alpha=(0,1)^{\mathrm T}$ 直接算 $p,q$ 验证。"},
        19: {"gs": r"由迹轮换 $\operatorname{tr}(ABXX^{\mathrm T})+\operatorname{tr}(XX^{\mathrm T}AB)=2X^{\mathrm T}ABX=2(AX)^{\mathrm T}(BX)>0$，故 $A,B$ 均可逆、$AB$ 可逆。$r_1=\mathrm r(AB)+\mathrm r(BC)=n+\mathrm r(C)$，$r_2=n+\mathrm r(C)$，$r_3=\mathrm r(A)+\mathrm r(AB)=2n$。故 $r_3\ge r_1=r_2$，选 C。",
            "yc": r"分块秩公式要求左上、右下块可逆可分块；这里 $AB$ 可逆故 $\begin{pmatrix}AB&O\\B&BC\end{pmatrix}$ 秩 $= \mathrm r(AB)+\mathrm r(BC)$。",
            "jq": r"条件推出 $AX,BX$ 对任意 $X\ne0$ 非零 $\Rightarrow A,B,AB$ 全可逆。",
            "zy": r"$\mathrm r(C)\le n$ 故 $r_1=r_2\le2n=r_3$；注意 $A^{\mathrm T}=A$ 用于迹等式。"},
        20: {"gs": r"由 $(A-4E)\alpha=0$ 且 $\alpha=(1,1,1)^{\mathrm T}$ 得 $A=E+\alpha\alpha^{\mathrm T}=\begin{pmatrix}2&1&1\\1&2&1\\1&1&2\end{pmatrix}$，特征值 $1,1,4$。$f=\begin{vmatrix}A&-X\\X^{\mathrm T}&0\end{vmatrix}=|A|X^{\mathrm T}A^{-1}X=X^{\mathrm T}A^*X$，其标准形为 $4y_1^2+4y_2^2+y_3^2$。",
            "yc": r"分块行列式降阶：$\begin{vmatrix}A&-X\\X^{\mathrm T}&0\end{vmatrix}=|A|\cdot X^{\mathrm T}A^{-1}X=X^{\mathrm T}A^*X$（$A^*=|A|A^{-1}$）。",
            "jq": r"谱分解：二重 $1$+单 $4$ 的实对称阵恰为 $E+\alpha\alpha^{\mathrm T}$（$\alpha^{\mathrm T}\alpha=3$）；$A^*$ 特征值为 $|A|/\lambda=4,4,1$。",
            "zy": r"正交变换 $X=QY$，$Q^{\mathrm T}A^*Q=\operatorname{diag}(4,4,1)$；标准形系数即 $A^*$ 特征值。"},
        21: {"gs": r"$A^{\mathrm T}=A$ 对称；$\alpha\alpha^{\mathrm T}$ 特征值 $1,0,0\Rightarrow A=E-2\alpha\alpha^{\mathrm T}$ 特征值 $-1,1,1$，$|A|=-1$。$A^*$ 特征值 $|A|/\lambda=1,-1,-1$，规范形 $y_1^2-y_2^2-y_3^2$，选 A。",
            "yc": r"$A^*$ 特征值 $=|A|/\lambda$（$\lambda\ne0$）；此处 $\lambda=1$ 对应 $A^*=-1$，勿反号。",
            "jq": r"秩 $1$ 矩阵 $uu^{\mathrm T}$ 特征值 $\{u^{\mathrm T}u,0,\dots\}$；单位向量 $u^{\mathrm T}u=1$。",
            "zy": r"$A$ 对称 $\Rightarrow A^*$ 对称，规范形由 $A^*$ 特征值符号定。"},
        22: {"gs": r"选 A（充分非必要）。充分：若 $A=P\Lambda P^{-1}$ 则 $A^2=P\Lambda^2P^{-1}$ 可对角化。必要不成立：反例 $A=\begin{pmatrix}0&1\\0&0\end{pmatrix}$，$A^2=O$ 已对角，但 $A$ 仅 $1$ 个无关特征向量不可对角化。",
            "yc": r"反例须取幂零阵（$A^2=O$ 但几何重数不足），非对角阵本身。",
            "jq": r"可对角化 $\Leftrightarrow$ 有 $n$ 个无关特征向量；幂 $A^k$ 可对角不回推 $A$。",
            "zy": r"充分性显然；必要性用 Jordan 块反例最直接。"},
        23: {"gs": r"$A=\begin{pmatrix}a&-1\\-1&a\end{pmatrix}$，$A^{-1}=\dfrac1{a^2-1}\begin{pmatrix}a&1\\1&a\end{pmatrix}$。代入不等式化简得 $\dfrac1{2(a+1)}(k_1-k_2)^2\ge0$ 对任意 $k_1,k_2$ 成立 $\Rightarrow a+1>0$ 且 $a^2-1\ne0$，故 $a\in(-1,1)\cup(1,+\infty)$。",
            "yc": r"$|A|=a^2-1\ne0$（否则 $A$ 不可逆不等式无意义）；化简注意 $\dfrac{a}{a^2-1}-\dfrac1{2(a-1)}=\dfrac1{2(a+1)}$。",
            "jq": r"把 $\alpha=(k_1,k_2)^{\mathrm T}$ 代入，合并 $k_1^2,k_2^2,k_1k_2$ 系数配成完全平方 $(k_1-k_2)^2$。",
            "zy": r"由 $(k_1-k_2)^2\ge0$ 恒成立推分母 $2(a+1)>0$，即 $a>-1$。"},
        24: {"gs": r"选 D。$Ax=0$ 解 $\subseteq Bx=0$ 解 $\Rightarrow B$ 行可由 $A$ 行表示，存在 $P$ 使 $AB=PA$；左乘 $\begin{pmatrix}E&-P\\O&E\end{pmatrix}$ 化 $\begin{pmatrix}A&AB\\O&A\end{pmatrix}$ 为 $\begin{pmatrix}A&O\\O&A\end{pmatrix}$。同理 $BA$ 也化为同块，故两方程组同解。",
            "yc": r"转置方向易混：$Ax=0\subseteq Bx=0$ 说的是行空间包含关系，推 $\begin{pmatrix}A&AB\\O&A\end{pmatrix}$ 而非 $BA$ 版。",
            "jq": r"行向量可表示 $\Rightarrow$ 存在 $P$ 使 $AB=PA$；初等行变换消去右上块。",
            "zy": r"$\begin{pmatrix}E&-B\\O&E\end{pmatrix}\begin{pmatrix}A&BA\\O&A\end{pmatrix}=\begin{pmatrix}A&O\\O&A\end{pmatrix}$ 同法证另一组。"},
        25: {"gs": r"选 A（充要）。充分：可对角化 $\Rightarrow\mathrm r(A-aE)=1,\mathrm r(A-bE)=2$，特征向量 $\xi_1,\xi_2,\xi_3$ 无关，逐列乘得 $(A-aE)(A-bE)=O$。必要：$(A-aE)(A-bE)=O\Rightarrow\mathrm r(A-aE)+\mathrm r(A-bE)\le3$，单根 $\mathrm r(A-bE)=2$ 推 $\mathrm r(A-aE)=1\Rightarrow$ 可对角化。",
            "yc": r"必要时须用 $\lambda_3=b$ 单根 $\Rightarrow\mathrm r(A-bE)=2$（几何重数 $=n-1$）；否则秩和不够。",
            "jq": r"独立特征向量个数 $=3-\mathrm r(A-aE)+3-\mathrm r(A-bE)\ge3$ 推出满 $3$ 个。",
            "zy": r"充分性亦可对角化 $\Leftrightarrow\mathrm r(A-aE)=1$（二重特征值几何重数 $2$）。"},
        26: {"gs": r"选 B。$\mathrm r(B_{n\times s})=n$（行满秩）$\Rightarrow\mathrm r(AB)=\mathrm r(A)$；且 $(A,AB)\sim(A,O)\Rightarrow\mathrm r(A,AB)=\mathrm r(A)$，故 $AB$ 列向量组与 $A$ 列向量组等价。",
            "yc": r"$B$ 是 $n\times s$ 行满秩，非列满秩；结论是列向量组等价，非行向量组。",
            "jq": r"两法：①列空间 $\operatorname{col}(AB)\subseteq\operatorname{col}(A)$ 且维数相等；②$B^{\mathrm T}A^{\mathrm T}x=0$ 与 $A^{\mathrm T}x=0$ 同解。",
            "zy": r"等价 $\Leftrightarrow$ 互相包含且同秩；本题列空间相等即等价。"},
    },
    "好题36-二次型最值问题": {
        1: {"gs": r"$B=\begin{pmatrix}1&-1\\-1&2\end{pmatrix}$ 正定，取 $D=\begin{pmatrix}1&-1\\0&1\end{pmatrix}$ 使 $B=D^{\mathrm T}D$。广义瑞利商 $\dfrac{f}{g}=\dfrac{x^{\mathrm T}Ax}{x^{\mathrm T}Bx}=\dfrac{z^{\mathrm T}Mz}{z^{\mathrm T}z}$，$M=(D^{-1})^{\mathrm T}AD^{-1}=\begin{pmatrix}1&-1\\-1&1\end{pmatrix}$，特征值 $2,0$，故 $\max=2$（取 $x_0=(0,\tfrac1{\sqrt2})^{\mathrm T}$）。",
            "yc": r"换元令 $Dx=z$ 时分母变 $z^{\mathrm T}z$，分子变 $z^{\mathrm T}Mz$；勿忘 $A=\begin{pmatrix}1&-2\\-2&4\end{pmatrix}$（$f=(x_1-2x_2)^2$ 半正定秩 $1$）。",
            "jq": r"广义瑞利商 $\max\dfrac{x^{\mathrm T}Ax}{x^{\mathrm T}Bx}=$ 矩阵 $(B^{-1/2})^{\mathrm T}A(B^{-1/2})$ 的最大特征值 $=M$ 的最大特征值。",
            "zy": r"$B=D^{\mathrm T}D$ 由 Cholesky/配方得；原书提示 $\dfrac{x^{\mathrm T}Ax}{x^{\mathrm T}Bx}$ 比 $\dfrac{x^{\mathrm T}Ax}{x^{\mathrm T}x}$ 更广，真题未现值得留意。"},
    },
}
