# -*- coding: utf-8 -*-
# 好题点睛 批次4：好题23~29（共 48 题）
# 四段规范：gs 公式 / yc 易错 / jq 技巧 / zy 注意
# LaTeX 全部用 r"..." 原始字符串承载。

TIPS = {
  "好题23-积分应用": {
    1: {"gs": r"令 $A=\iint_D f(xy)\,\mathrm{d}\sigma$，$D$ 由 $y=|x|^3$ 与 $y=1$ 围成，$S_D=2\int_0^1(1-x^3)\mathrm{d}x=\frac32$。换元 $u=x^2-t^2$ 得 $\int_0^x t f(x^2-t^2)\mathrm{d}t=\frac12\int_0^{x^2}f(u)\mathrm{d}u$；被积 $xy\int_0^{(xy)^2}f$ 关于 $x$ 为奇函数 $\Rightarrow$ 该项积分为 $0$，故 $A(1-S_D)=aS_D\Rightarrow A=-3a$。",
       "yc": r"① 右端 $\int_0^x t f(x^2-t^2)\mathrm{d}t$ 换元易错写成 $\int_0^{x^2}$；② 漏掉“区域关于 $y$ 轴对称 + 被积关于 $x$ 奇”才使 $\iint=0$，否则解不出 $A$。",
       "jq": r"见“区域对称 + 积分方程含 $\iint_D f\,\mathrm{d}\sigma$ 常数 $A$”套路：先令 $A=\iint_D f$，两边再在 $D$ 上积分，化为 $A$ 的一元一次方程。",
       "zy": r"解题不需求 $f(x)$ 显式，只需用对称性消去 $\iint$ 项；本题消项是靠 $xy\int_0^{(xy)^2}f$ 的奇性。"},
    2: {"gs": r"令 $u=x^2-t$，则 $\int_0^{x^2}f(x^2-t)\mathrm{d}t=\int_0^{x^2}f(u)\mathrm{d}u$；$D$ 由 $y=x^3$ 与 $y=\pm1$ 围成（关于原点对称），$g(x,y)=(x+y)\int_0^{(x+y)^2}f$ 为奇 $\Rightarrow\iint_D g=0$，得 $A=-3a$；$f(x)=x\int_0^{x^2}f+A+a$，由 $f(1)=0$ 与平均值 $\int_0^1 f=3$ 联立得 $a=\frac32$。",
       "yc": r"① $D$ 面积 $S_D=\frac32$（非 $2$）；② 把“平均值 $3$”误当 $f(1)$ 或 $f(0)$；③ 漏用 $f(1)=0$ 与 $\int_0^1 f=3$ 两条件联立。",
       "jq": r"同第 1 题套路令 $A=\iint_D f$，靠区域关于原点对称消 $\iint$ 项；再分别用 $f(1)=0$ 与平均值条件定 $a$。",
       "zy": r"本题 $D$ 关于原点对称，消项靠 $(x+y)\int f$ 的奇性，与第 1 题消项原因不同，别混。"},
    3: {"gs": r"对 $y$ 累次并凑 $\mathrm{d}f(x+y)$ 分部：$\iint_D y f'(x+y)\mathrm{d}\sigma=\int_0^1(1-x)f(1)\mathrm{d}x-\iint_D f(x+y)\mathrm{d}\sigma=\frac12-k$（$k=\iint_D f$，$f(1)=1$）。代入得 $k=\iint\frac{x+y}{1+x+y}+\frac14-\frac{k}{2}$，其中 $\iint\frac{x+y}{1+x+y}=2\iint\frac{x}{1+x+y}=\ln2-\frac12$，故 $k=\frac23\ln2-\frac16$。",
       "yc": r"① 分部时把 $(1-x)f(1)$ 错写成 $(1-x)f(x+y)$，$f(1)=1$ 是定值；② 对称性 $\iint\frac{x+y}{1+x+y}=2\iint\frac{x}{1+x+y}$ 易漏系数 $2$。",
       "jq": r"积分方程含未知常数 $k=\iint_D f$，两边在 $D$ 上积分化为 $k$ 的方程；$\iint\frac{x}{1+x+y}$ 用 $\int x[\ln2-\ln(1+x)]\mathrm{d}x$ 配方。",
       "zy": r"区域 $D$ 为 $x+y=1$ 与两轴围成，面积 $\frac12$；$f(1)=1$ 是常数，分部时固定不随 $y$ 变。"},
    4: {"gs": r"结论：若 $f(x+T)=f(x)$ 且 $f$ 偶，则 $\int_0^{nT}x f(x)\mathrm{d}x=\frac{n^2T}{2}\int_0^T f(x)\mathrm{d}x$。证：令 $x=nT-t$ 得 $\int_0^{nT}xf=nT\int_0^{nT}f-\int_0^{nT}tf$，移项 + 周期性。特例 $\int_0^{n\pi}x|\cos x|\mathrm{d}x=n^2\pi$（$|\cos x|$ 周期 $\pi$，$\int_0^\pi|\cos x|\mathrm{d}x=2$）。",
       "yc": r"① 直接用 $\int_0^{nT}f=n\int_0^T f$ 时忘了 $f$ 需以 $T$ 为周期；② 误把 $|\cos x|$ 当周期 $2\pi$，实际周期 $\pi$，$\int_0^\pi=2\neq0$。",
       "jq": r"轮换代换 $x\to nT-t$ 制造“$\int xf$”与“$\int tf$”同式，相加消元；遇周期偶函数优先套公式。",
       "zy": r"公式要求 $f$ 同时满足“周期 $T$”与“偶函数”；只周期不偶则代换后 $f(nT-t)=f(-t)\neq f(t)$。"},
    5: {"gs": r"体积 $V=V_1-V_2$，$V_1=\frac{2\pi}{3}$（半球），$V_2=\pi\int_0^1 y^2\mathrm{d}x$（星形线 $y=(1-x^{2/3})^{3/2}$）$\to\frac{16\pi}{105}$，故 $V=\frac{18\pi}{35}$；表面积 $S=S_1+S_2$，$S_1=2\pi$（半球面），$S_2=2\pi\int y\,\mathrm{d}s$（$\mathrm{d}s=3\sin t\cos t\,\mathrm{d}t$）$\to\frac{6\pi}{5}$，故 $S=\frac{16\pi}{5}$。",
       "yc": r"① 星形线显式 $y=(1-x^{2/3})^{3/2}$ 易写错（漏 $3/2$ 次方）；② 体积用 $\pi\int y^2\mathrm{d}x$ 但参数化时 $\mathrm{d}x$ 符号别错；③ 表面积 $S_2$ 用 $2\pi\int y\,\mathrm{d}s$（旋转侧面积是曲线转，非 $2\pi\int y\,\mathrm{d}x$）。",
       "jq": r"达标题拆成“大体积-小体积”“外表面+内表面”；星形线参数 $x=\cos^3t,y=\sin^3t$，Wallis 公式算 $\int\sin^n$。",
       "zy": r"绕 $x$ 轴：体积是圆盘法（$\pi\int y^2\mathrm{d}x$），表面积是 $2\pi\int y\,\mathrm{d}s$；两曲线交点 $(1,0),(0,1)$，体积相减、表面积相加。"},
    6: {"gs": r"去绝对值得四段：$xy=\mathrm{e}$（$x,y\ge1$）；$y=\frac{x}{\mathrm{e}}$（$x\ge1,0<y<1$）；$y=\mathrm{e}x$（$0<x<1,y\ge1$）；$xy=\frac1{\mathrm{e}}$（$0<x,y<1$）。面积 $A=\int_{1/\mathrm{e}}^1(\mathrm{e}x-\frac{1}{\mathrm{e}x})\mathrm{d}x+\int_1^{\mathrm{e}}(\frac{\mathrm{e}}{x}-\frac{x}{\mathrm{e}})\mathrm{d}x=\mathrm{e}-\frac1{\mathrm{e}}$（选 D）。换元 $u=\ln x,v=\ln y$ 得 $|u|+|v|\le1$，雅可比 $\mathrm{e}^{u+v}$，同样得 $\mathrm{e}-\frac1{\mathrm{e}}$。",
       "yc": r"① 去绝对值分段易漏一段（四段而非两段）；② 选项 D $=\mathrm{e}-\frac1{\mathrm{e}}$ 与 $\mathrm{e}+\frac1{\mathrm{e}}$ 混淆。",
       "jq": r"两法——代数分段积分，或令 $x=\mathrm{e}^u,y=\mathrm{e}^v$ 化菱形 $|u|+|v|\le1$，雅可比 $\mathrm{e}^{u+v}$。",
       "zy": r"面积恒正，结果 $\mathrm{e}-\frac1{\mathrm{e}}>0$；换元后雅可比 $|\partial(x,y)/\partial(u,v)|=\mathrm{e}^{u+v}>0$。"},
    7: {"gs": r"方程 $(y-\mathrm{e}^{x-1})\mathrm{d}x+\mathrm{d}y=0\Rightarrow y'+y=\mathrm{e}^{x-1}$，通解 $y=\frac12\mathrm{e}^{x-1}+C\mathrm{e}^{-x}$，$y(1)=1\Rightarrow C=\frac{\mathrm{e}}{2}$，故 $y=\frac12(\mathrm{e}^{x-1}+\mathrm{e}^{-(x-1)})$。侧面积 $\mathrm{d}S=2\pi(x-1)\,\mathrm{d}s$，由 $y'^2=y^2-1$（$x\ge1,y'\ge0$）得 $x-1=\ln(y+\sqrt{y^2-1})$，$x_y'=\frac1{\sqrt{y^2-1}}$，积分得 $S_{\text{侧}}=2\pi(1-\mathrm{e}^{-1})$。",
       "yc": r"① 绕 $x=1$ 旋转，半径是 $(x-1)$ 非 $x$；② 误用 $\mathrm{d}S=2\pi y\,\mathrm{d}s$（绕 $x$ 轴才是），绕竖直线应 $2\pi(x-1)\mathrm{d}s$；③ $y'^2=y^2-1$ 由 $y'+y=\mathrm{e}^{x-1}$ 平方关系推，别直接对显式代。",
       "jq": r"双曲函数法 $y=\cosh(x-1)$ 更简；侧面积微元绕竖线用半径 $(x-1)\times$ 弧长元 $\mathrm{d}s$；降次用 $x-1$ 表为 $y$ 的函数再对 $y$ 积分。",
       "zy": r"本题（Ⅰ）原扫描页缺解析，按一阶线性方程标准法补；曲线关于 $x=1$ 对称，只算 $x\ge1$ 半侧即可。"},
  },
  "好题24-微分方程的通特解": {
    1: {"gs": r"法一：令 $z=xy$，由通解结构知 $z$ 的特征方程 $(r-1)(r-2)=0\Rightarrow z''-3z'+2z=0$，代 $z=xy$ 得 $xy''-(3x-2)y'+(2x-3)y=0$。法二：对 $xy=c_1\mathrm{e}^x+c_2\mathrm{e}^{2x}$ 连求两导，消 $c_1,c_2$ 得同式。",
       "yc": r"① 把通解误认成 $y$ 的通解，漏掉 $z=xy$ 代换；② 法二代 $c_1\mathrm{e}^x,c_2\mathrm{e}^{2x}$ 表达式时符号易错（$c_2\mathrm{e}^{2x}=\frac14(2xy''-2xy'-2y+4y')$）。",
       "jq": r"由通解结构知特征根 $1,2$，先列 $z$ 的常系数方程最稳；要 $x,y$ 混的方程再用代入法。",
       "zy": r"答案含 $x$ 因子是变系数方程（二阶线性），非常系数齐次；特征法只对 $z=xy$ 成立。"},
    2: {"gs": r"分部积分（$f(1)=0$）：$\int_0^1 f(x)\mathrm{d}x=-\int_0^1 x f'(x)\mathrm{d}x$。原式 $=\int_0^1(f'(x)+3x)^2\mathrm{d}x-\int_0^1 9x^2\mathrm{d}x+3=\int_0^1(f'(x)+3x)^2\mathrm{d}x=0$（因 $\int_0^1 9x^2\mathrm{d}x=3$）。故 $f'(x)+3x=0\Rightarrow f(x)=\frac32(1-x^2)$。",
       "yc": r"① 分部时 $\int_0^1 f$ 应为 $-\int_0^1 x f'$（不是 $+$）；② 漏“$\int_0^1 9x^2\mathrm{d}x=3$”这一步才把 $+3$ 消成平方和为 $0$。",
       "jq": r"见 $\int f'^2$ 与 $\int f$ 同题，必想分部积分把 $\int f$ 转成含 $f'$ 的式，再配完全平方 $=0$。",
       "zy": r"连续函数平方积分 $=0\Rightarrow$ 该函数 $\equiv0$（非“可去”）；故 $f'(x)+3x\equiv0$ 严格成立。"},
    3: {"gs": r"全 $\mathbb{R}$ 有界 $\Rightarrow$ 特征根不能有非零实根（$\mathrm{e}^{\lambda x}$ 无界），重根 $\lambda$ 时 $x\mathrm{e}^{\lambda x}$ 无界（$\lambda=0$ 时 $y=x$ 仍无界），共轭复根 $\alpha\pm\beta\mathrm{i}$ 当 $\alpha=0$ 才有界。由 $\alpha=-\frac{a}{2}=0$ 且 $\Delta<0$ 得 $a=0,b>0$（选 C）。",
       "yc": r"① 误认为“有界只需 $b>0$”，忽略 $a=0$；② 重根情形 $\lambda=0$ 时解为线性函数仍无界，故 $\Delta=0$ 也不行；③ 把 $\alpha$ 符号搞反（$\alpha=-a/2$）。",
       "jq": r"分 $\Delta>0/\Delta=0/\Delta<0$ 三种讨论；核心判据“$\mathrm{e}^{\text{非零实}\lambda x}$ 与 $x\mathrm{e}^{\lambda x}$ 均无界”，唯一有界是纯虚根。",
       "zy": r"题目问“解（全部）在 $\mathbb{R}$ 上有界”，任一根产生无界解即排除；故选 C（$a=0,b>0$）对应纯虚根。"},
    4: {"gs": r"令 $x=\mathrm{e}^t$，则 $x^2y''+xy'-9y=0$ 化为 $\frac{\mathrm{d}^2y}{\mathrm{d}t^2}-9y=0$，通解 $y=C_1x^3+C_2x^{-3}$；由 $y(1)=2,y'(1)=6$ 得 $C_1=2,C_2=0\Rightarrow y=2x^3$。积分 $\int_1^2 2x^3\sqrt{4-x^2}\mathrm{d}x=\frac{22\sqrt3}{5}$（令 $t=4-x^2$ 或 $x=2\sin t$）。",
       "yc": r"① 欧拉方程代换 $x=\mathrm{e}^t$ 后 $\frac{\mathrm{d}^2y}{\mathrm{d}x^2}=\frac1{x^2}(\frac{\mathrm{d}^2y}{\mathrm{d}t^2}-\frac{\mathrm{d}y}{\mathrm{d}t})$，常漏减 $\frac{\mathrm{d}y}{\mathrm{d}t}$ 项；② 由 $x=1$ 初值求 $C_1,C_2$ 时混淆 $y$ 与 $y'$ 方程。",
       "jq": r"欧拉方程标准代换 $x=\mathrm{e}^t$（或 $t=\ln x$）；积分 $\int x^3\sqrt{4-x^2}$ 用 $t=4-x^2$ 配 $(4-t)\sqrt{t}$ 最省。",
       "zy": r"欧拉方程形如 $x^ny^{(n)}+\cdots$，本题阶数 $2$，特征 $r(r-1)+r-9=r^2-9=0\Rightarrow r=\pm3$。"},
    5: {"gs": r"$\frac{\partial(2y-3x)}{\partial y}=2=\frac{\partial(2x-5y)}{\partial x}$，全微分成立。$F(x,y)=\int(2y-3x)\mathrm{d}x=2xy-\frac32x^2+\varphi(y)$，由 $F_y=2x-5y$ 得 $\varphi'(y)=-5y\Rightarrow\varphi=-\frac52y^2+C$。代入 $(1,1)$ 得 $C=2$，故 $2xy-\frac32x^2-\frac52y^2+2=0$。",
       "yc": r"① 全微分条件 $\partial P/\partial y=\partial Q/\partial x$ 不验证直接积；② 对 $x$ 积分后 $+\varphi(y)$ 漏掉，或 $\varphi(y)$ 由 $F_y$ 求时算错符号（应为 $-5y$ 非 $+5y$）。",
       "jq": r"全微分方程先验证 $P_y=Q_x$；取偏导简单的变量先积（本题 $\partial F/\partial x$ 简单），再对 $y$ 比对求 $\varphi(y)$。",
       "zy": r"答案可写成 $4xy-3x^2-5y^2+4=0$（同乘 $2$）；题设 $y(1)=1$ 确定常数 $C$。"},
  },
  "好题25-微分方程的应用": {
    1: {"gs": r"对角线 $s^2=l^2+w^2$，两边对 $t$ 求导：$s\frac{\mathrm{d}s}{\mathrm{d}t}=l\frac{\mathrm{d}l}{\mathrm{d}t}+w\frac{\mathrm{d}w}{\mathrm{d}t}$。$l=12,w=5\Rightarrow s=13$；$13\frac{\mathrm{d}s}{\mathrm{d}t}=12\times2+5\times3=39\Rightarrow\frac{\mathrm{d}s}{\mathrm{d}t}=3\ \mathrm{cm/s}$。",
       "yc": r"① 直接对 $s$ 求导漏掉 $s$（应为 $s\cdot s'$ 非 $s'$）；② 代入时 $l,w$ 是瞬时值非速率。",
       "jq": r"相关变化率统一套路——建关系 $\to$ 两边对 $t$ 求导 $\to$ 代入已知瞬时值。",
       "zy": r"$\frac{\mathrm{d}l}{\mathrm{d}t}=2,\frac{\mathrm{d}w}{\mathrm{d}t}=3$ 是速率（带单位 $\mathrm{cm/s}$）；问的是 $\frac{\mathrm{d}s}{\mathrm{d}t}$ 也带单位。"},
    2: {"gs": r"同好题18-2。$\frac{\mathrm{d}y}{\mathrm{d}x}=\frac{y}{x+\sqrt{x^2+y^2}}$，令 $\frac{x}{y}=u\Rightarrow\frac{\mathrm{d}u}{\sqrt{1+u^2}}=\frac{\mathrm{d}y}{y}$，积分得 $u+\sqrt{1+u^2}=C_2y$，$y(0)=1\Rightarrow C_2=1$，故 $y=\sqrt{1+2x}$。",
       "yc": r"① 把 $|OM|=|ON|$ 误写成几何比例错（$MP/NP=y/(x+\sqrt{x^2+y^2})$，$NP=\sqrt{x^2+y^2}+x$）；② 与好题18-2 重复却漏记结论。",
       "jq": r"切线截距/距离类统一用“垂足 $P$、比值 $\mathrm{d}y/\mathrm{d}x=MP/NP$”；齐次方程令 $u=x/y$ 降次。",
       "zy": r"本题与好题18 第 2 题完全相同，可互相印证；$y>0$ 故开方取正。"},
    3: {"gs": r"上凸 $y''<0$，曲率 $K=\frac{|y''|}{(1+y'^2)^{3/2}}=\frac{1}{\sqrt{1+y'^2}}\Rightarrow y''=-(1+y'^2)$。令 $p=y'$，则 $\frac{\mathrm{d}p}{1+p^2}=-\mathrm{d}x\Rightarrow p=\tan(\frac{\pi}{4}-x)$；积分 $y=\ln[\cos(\frac{\pi}{4}-x)]+1+\frac12\ln2$。",
       "yc": r"① 上凸漏 $y''<0$ 直接写 $y''=\cdots$，导致曲率公式 $|y''|$ 处理错；② 由 $y(0)=1$ 定 $C_2$ 时漏 $\frac12\ln2$。",
       "jq": r"曲率题先由凹凸定 $y''$ 符号去掉绝对值，再降阶 $p=y'$；初值 $y(0)=1,y'(0)=1$。",
       "zy": r"$y=\ln\cos(\cdots)$ 定义域 $-\frac{\pi}{4}<x<\frac{3\pi}{4}$（$\cos>0$）；结果含自然对数非反三角。"},
    4: {"gs": r"法一：$\frac{\mathrm{d}\alpha}{\mathrm{d}x}=\frac{\mathrm{d}y}{\mathrm{d}x}\Rightarrow\alpha=y+C_1$，$\tan\alpha=y'\Rightarrow\frac{\mathrm{d}\alpha}{\mathrm{d}x}=\frac{\sin\alpha}{\cos\alpha}$，分离得 $\sin\alpha=C_2\mathrm{e}^x$，$\alpha(0)=\frac{\pi}{4}\Rightarrow y=\arcsin\frac{\mathrm{e}^x}{\sqrt2}-\frac{\pi}{4}$（$x\le0$）。法二：$\tan\alpha=y'\Rightarrow\alpha=\arctan y'$，$\frac{\mathrm{d}\alpha}{\mathrm{d}x}=\frac{y''}{1+y'^2}=y'$，降阶 $p'=p(1+p^2)$。",
       "yc": r"① 法二把 $y''/(1+y'^2)=y'$ 错写成 $=y$；② 由 $(y')^2=\frac{\mathrm{e}^{2x}}{2-\mathrm{e}^{2x}}$ 开方取正（$y'(0)=1>0$）别取负；③ 定义域 $x\le0$（$\mathrm{e}^x/\sqrt2\le1$）。",
       "jq": r"倾角 $\alpha$ 与斜率 $y'$ 关系 $\tan\alpha=y'$；两路都行——直接积 $\alpha=y+C$ 或降阶 $y''$ 方程。",
       "zy": r"曲线与直线 $y=x$ 切于原点 $\Rightarrow y(0)=0,y'(0)=1$；$\arcsin$ 定义域要求 $\mathrm{e}^x/\sqrt2\le1$。"},
    5: {"gs": r"同好题18-1。$a\int_0^x|y|\mathrm{d}t=\int_0^x\sqrt{1+y'^2}\mathrm{d}t$，求导 $a|y|=\sqrt{1+y'^2}$，$y'=\pm\sqrt{a^2y^2-1}$；取正支积分得 $ay+\sqrt{a^2y^2-1}=\mathrm{e}^{ax}$，两式相加 $y=\frac{\mathrm{e}^{ax}+\mathrm{e}^{-ax}}{2a}$。",
       "yc": r"① 漏绝对值 $|y|$（面积非负）；② 两式 $ay\pm\sqrt{a^2y^2-1}=\mathrm{e}^{\pm ax}$ 相加时把 $\sqrt{\cdots}$ 抵消看不清；③ 与好题18-1 重复。",
       "jq": r"弧长与面积关系题，两边对上限求导转出 $y'$ 方程；对称式相加消根号。",
       "zy": r"本题与好题18 第 1 题相同；$y(0)=1/a$ 给出初值，对应双曲余弦 $y=\cosh(ax)/a$。"},
    6: {"gs": r"$m\frac{\mathrm{d}v}{\mathrm{d}t}=-kv$，又 $\frac{\mathrm{d}v}{\mathrm{d}t}=\frac{\mathrm{d}v}{\mathrm{d}x}\cdot\frac{\mathrm{d}x}{\mathrm{d}t}=v\frac{\mathrm{d}v}{\mathrm{d}x}\Rightarrow\mathrm{d}x=-\frac{m}{k}\mathrm{d}v$，积分 $x=\frac{m}{k}(v(0)-v)$。总位移 $x_\infty=\frac{mv(0)}{k}$；半位移时 $x=\frac{mv(0)}{2k}=\frac{m}{k}(v(0)-v)\Rightarrow v=\frac{v(0)}{2}$（选 B）。",
       "yc": r"① 忘记 $v'=\frac{\mathrm{d}v}{\mathrm{d}x}\cdot v$ 的链式法则，直接对 $t$ 积分求不出“位移一半”；② 把总位移当 $v(0)$ 而非 $\frac{mv(0)}{k}$。",
       "jq": r"物理题求“位移相关”量，把 $a=\frac{\mathrm{d}v}{\mathrm{d}t}$ 改写为 $v\frac{\mathrm{d}v}{\mathrm{d}x}$ 消去 $t$；本题不需求时间 $t$。",
       "zy": r"问“滑行至总位移一半时的速度”，用能量式 $x=\frac{m}{k}(v_0-v)$ 直接联立半位移；答案与质量 $m$、$k$ 无关。"},
    7: {"gs": r"$S=\frac{x^2}{4\pi}+\frac{y^2}{16}+\frac{\sqrt3}{36}z^2$，约束 $x+y+z=2$。Lagrange：$x=-2\pi\lambda,y=-8\lambda,z=-6\sqrt3\lambda$，代约束 $\lambda=-\frac{1}{\pi+4+3\sqrt3}$，最小 $S=\frac{1}{\pi+4+3\sqrt3}$。边界值 $\frac{1}{4+3\sqrt3},\frac{1}{\pi+3\sqrt3},\frac{1}{\pi+4}$ 均更大。",
       "yc": r"① 正三角形面积 $\frac12(\frac{z}{3})^2\sin\frac{\pi}{3}=\frac{\sqrt3}{36}z^2$ 易漏 $\frac{\sqrt3}{36}$（误为 $\frac{z^2}{36}$ 或 $\frac{z^2}{12}$）；② 只求驻点不验证边界（闭区域最值需比边界）。",
       "jq": r"周长分配类用 Lagrange；比较边界三点（某段长为 $0$）确认是最小非最大。",
       "zy": r"连续函数在有界闭区域必取最值，驻点 + 三条边界最小值比较，得全局最小。"},
    8: {"gs": r"切线 $y$ 轴截距 $y-xy'$；弧长 $\int_1^x\sqrt{1+y'^2}\mathrm{d}t=|y-xy'|$。令 $x=1$ 得 $y'(1)=1$。$f(x)=y-xy'$，$f'=-xy''<0$（$x\ge1,y''>0$）$\Rightarrow f\le0$，故等式为 $xy'-y$。求导 $\sqrt{1+y'^2}=xy''$，令 $p=y'$ 得 $p+\sqrt{1+p^2}=(1+\sqrt2)x$，解得 $y=\frac14(1+\sqrt2)x^2-\frac{1}{2(1+\sqrt2)}\ln x+\frac34-\frac{\sqrt2}{4}$。",
       "yc": r"① 截距符号：$y-xy'$ 在 $x\ge1$ 因 $f'<0$ 而 $\le0$，去绝对值变 $xy'-y$ 易错向；② 由 $p+\sqrt{1+p^2}=Cx$ 反解 $p$ 用共轭式 $\sqrt{1+p^2}-p=\frac{1}{Cx}$；③ $y'(1)=1$ 由 $x=1$ 代入弧长式得。",
       "jq": r"截距类先令 $x=1$ 定 $y'(1)$；判断 $f(x)=y-xy'$ 单调性去绝对值；$y''$ 方程令 $p=y'$ 分离。",
       "zy": r"$x\ge1,y'>0,y''>0$ 保证 $y-xy'\le0$，绝对值方向固定；$C_1=1+\sqrt2$ 由 $p(1)=1$ 定。"},
  },
  "好题26-多元微分概念问题": {
    1: {"gs": r"$f(x,y)=1$ 当 $0<y<x^2$ 否则 $0$。沿 $y=kx$：$|kx|>x^2$（$x$ 小）$\Rightarrow\lim f=0$（①对）；沿 $y=\frac{x^2}{2}$ 得 $1$、沿 $y=-x^2$ 得 $0\Rightarrow$ 二重极限不存在 $\Rightarrow$ 不连续 $\Rightarrow$ 不可微（②④错）；偏导 $f_x=f_y=0$（③对）。共 $2$ 个，选 B。",
       "yc": r"① 误以为“沿任意直线极限存在”即二重极限存在（反例 $y=cx^2$ 是曲线）；② 偏导存在就认为可微（本题不可微）；③ 漏“可微必连续”反推。",
       "jq": r"分段/指示函数判连续性，找两条路径极限不同（如 $y=cx^2$ 与 $y=-x^2$）；偏导用定义直接算。",
       "zy": r"①沿直线 $y=kx$ 全为 $0$（因 $x$ 足够小 $|kx|>x^2$），但曲线路径可破；②偏导存在 $\neq$ 连续 $\neq$ 可微。"},
    2: {"gs": r"D：$\Delta f=[(\Delta x)^2+(\Delta y)^2]\sin\frac{1}{(\Delta x)^2+(\Delta y)^2}$。偏导 $f_x=f_y=0$；$\lim\frac{\Delta f}{\rho}=\rho\cdot\sin\frac{1}{\rho^2}\to0$，故可微且 $\mathrm{d}f=0$（选 D）。A 仅偏导存在推不出可微；B 的 $\frac{\Delta x\Delta y}{\rho}$ 除 $\rho$ 后 $\frac{\Delta x\Delta y}{\rho^2}$ 沿 $\Delta y=k\Delta x$ 不存在；C 的 $f_x$ 用 $|\Delta x|$ 左右极限 $\pm1$ 不存在。",
       "yc": r"① 见 A 偏导为 $0$ 误判可微；② B 把 $\frac{\Delta x\Delta y}{\sqrt{\Delta x^2+\Delta y^2}}$ 当高阶无穷小（实际除 $\rho$ 后 $=\frac{\Delta x\Delta y}{\rho^2}$ 不存在）；③ C 误认 $\frac{\sin}{\left|\cdot\right|}$ 有极限。",
       "jq": r"可微判定用定义 $\lim\Delta f/\rho=0$；给 $\rho\cdot(\text{有界量})$ 形式直接得 $0$；给 $\frac{\Delta x\Delta y}{\rho}$ 形式用 $\Delta y=k\Delta x$ 反例否定。",
       "zy": r"可微 $\Rightarrow\mathrm{d}f=A\Delta x+B\Delta y$ 且余项 $/\rho\to0$；$A,B$ 恰为偏导。$\mathrm{d}f=0$ 需偏导均 $0$ 且极限成立。"},
  },
  "好题27-多元函数偏导与表达式": {
    1: {"gs": r"$z_{xx}=z_{uu}+2z_{uv}+z_{vv}$，$z_{xy}=a z_{uu}+(a+b)z_{uv}+b z_{vv}$，$z_{yy}=a^2z_{uu}+2ab z_{uv}+b^2z_{vv}$。代入得系数 $3-4a+a^2=0$ 且 $3-4b+b^2=0$，$a<b\Rightarrow a=1,b=3$。$z=f(x+y)+g(x+3y)$，由 $z(x,0)=\sin x,z_y'(x,0)=0$ 解得 $z=\frac32\sin(x+y)-\frac12\sin(x+3y)$。",
       "yc": r"① 复合求导 $z_{xy}$ 系数 $(a+b)$ 易错成 $a$ 或 $b$；② 解 $a,b$ 时两方程同根 $\{1,3\}$，$a<b$ 才定 $a=1$；③ $f,g$ 由初值联立 $f'+g'=\cos x,f'+3g'=0$ 解反。",
       "jq": r"特征方程法匹配系数（$u=x+ay$ 对应根 $a$）；化简后 $z=f(u)+g(v)$ 直接积分；初值表成 $f,g$ 方程组。",
       "zy": r"$a<b$ 是题设，去掉会多解；验证 $z(x,0)=\sin x$、$z_y'=0$ 可自检。"},
    2: {"gs": r"$f_x'=1+2\cos x\Rightarrow f(x,y)=x+2\sin x+g(y)$。由 $f(x,\sin x)=x+\sin x$ 得 $g(\sin x)=-\sin x\Rightarrow g(y)=-y$，故 $f=x+2\sin x-y$，$f_y'|_{y=\sin x}=-1$。",
       "yc": r"① 由 $f_x$ 积分时把 $g(y)$ 漏掉（应为 $x+2\sin x+g(y)$ 非 $x+2\sin x$）；② $g(\sin x)=-\sin x$ 推 $g(y)=-y$ 需认出变量替换。",
       "jq": r"已知 $f_x$ 求 $f$ 先对 $x$ 积 $+g(y)$；再用特殊关系 $f(x,\sin x)$ 定 $g$。",
       "zy": r"$f_y'$ 在 $y=\sin x$ 处求值，结果就是 $-1$（常数），与 $x$ 无关。"},
    3: {"gs": r"$F(x,t)=f(x,\int_1^t\ln x\,\mathrm{d}x)$。$F_x'=f_1'$，$F_t'=f_2'\cdot\ln t$。令 $x=0$ 需 $\int_1^{t(0)}\ln x\,\mathrm{d}x=1$（因 $f(0,1)=0$）$\Rightarrow t(0)=\mathrm{e}$。在 $(0,\mathrm{e})$ 处 $F_t'=f_y'(0,1)\cdot\ln\mathrm{e}=1\neq0$，故可确定 $t=t(x)$，$t'(0)=-\frac{F_x'}{F_t'}=-f_x'(0,1)$（选 C）。",
       "yc": r"① 误在 $(0,1)$ 处判定（此时 $\int_1^1\ln x\,\mathrm{d}x=0\neq1$，$f(0,0)$ 未必 $0$）；② 把 $F_t'$ 中 $\ln t$ 在 $t=\mathrm{e}$ 处值忘算（$\ln\mathrm{e}=1$）；③ $t'(0)$ 符号 $-F_x'/F_t'$ 别漏负号。",
       "jq": r"隐函数存在定理先定“哪个点使内层 $=$ 已知零点”——解 $\int_1^{t_0}\ln x\,\mathrm{d}x=1$ 得 $t_0=\mathrm{e}$；再算 $F_t'\neq0$。",
       "zy": r"选项考的是 $(0,\mathrm{e})$ 非 $(0,1)$；$f(0,1)=0$ 与 $f_y'(0,1)=1$ 是判定关键。"},
    4: {"gs": r"（Ⅰ）裂项相加 $f(x)-f(x/2^n)=\sum_{k=1}^n\ln\cos\frac{x}{2^k}$；用 $\sin\theta=2\sin\frac{\theta}{2}\cos\frac{\theta}{2}$ 得 $\lim\ln[\cos\frac{x}{2}\cdots\cos\frac{x}{2^n}]=\ln\frac{\sin x}{x}$，故 $f(x)=\ln\frac{\sin x}{x}$（$x\neq0$），$f(0)=0$。（Ⅱ）$f'(x)=\frac{\cos x}{\sin x}-\frac1x$（$x\neq0$），$f'(0)=0$；$\lim_{x\to0}f'=0=f'(0)$，故 $f'$ 在 $(-\pi,\pi)$ 连续。",
       "yc": r"① 裂项求和漏最后一项或无穷乘积收敛判断错；② $f'(0)$ 用定义 $\lim\frac{\ln(\sin x/x)}{x}$，误用洛必达得错值（应为 $0$）；③ 连续判定需 $\lim_{x\to0}f'(x)=f'(0)$。",
       "jq": r"函数方程 $f(x)=f(x/2)+\cdots$ 用“裂项 $\to$ 无穷乘积 $\to$ 正弦倍角公式”；$f'(0)$ 用定义（导数公式在 $0$ 不适用）。",
       "zy": r"只在 $x\neq0$ 有 $f'(x)=\cot x-\frac1x$；$x=0$ 单独用定义，且需验证极限一致。"},
    5: {"gs": r"法一：解 $u=x+y,v=y/x\Rightarrow x=\frac{u}{1+v},y=\frac{uv}{1+v}$，$f=u^2\frac{1-v}{1+v}=u^2(\frac{2}{1+v}-1)$。$f_u|_{(1,1)}=0$，$f_v|_{(1,1)}=-\frac12$（选 D）。法二：两边微分比较 $\mathrm{d}x,\mathrm{d}y$ 系数。",
       "yc": r"① 解出 $x,y$ 后代 $x^2-y^2$ 化简错（应为 $u^2\frac{1-v^2}{(1+v)^2}=u^2\frac{1-v}{1+v}$）；② 在 $(u,v)=(1,1)$ 对应 $(x,y)=(\frac12,\frac12)$ 易漏；③ 法二微分比较系数易算错 $y/x$ 的 $\mathrm{d}v$。",
       "jq": r"复合求偏导两法——解出显式 $f(u,v)$ 或两边微分比对；本题解显式最简。",
       "zy": r"求 $f_u,f_v$ 在点 $(u,v)=(1,1)$，需先把 $(u,v)=(1,1)$ 反解 $(x,y)=(\frac12,\frac12)$ 才代入微分方程组。"},
    6: {"gs": r"$g(x,y)=u(x+y,x-y)$，$g_y=u_1'-u_2'=2(x+y)\cos2x$；积分 $g=(2xy+y^2)\cos2x+\varphi(x)$，$g(x,0)=0\Rightarrow\varphi=0$。令 $s=x+y,t=x-y$，反解 $u(s,t)=\frac{3s^2-t^2-2st}{4}\cos(s+t)$，$u(1,0)=\frac34\cos1$（选 D）。",
       "yc": r"① $g_y$ 应先算 $u_1'-u_2'$ 再代 $s=x+y,t=x-y$ 得 $2(x+y)\cos2x$，别漏 $2$；② 反解 $s,t$ 时代 $u(s,t)$ 展开 $\frac{3s^2-t^2-2st}{4}$ 易错符号；③ $u(1,0)$ 非 $u(0,0)$。",
       "jq": r"构造 $g=u(s,t)$ 用新变量简化；先求 $g$ 再反解 $u(s,t)$ 代入目标点。",
       "zy": r"$g(x,0)=0$ 用于定 $\varphi(x)=0$；最终 $u(1,0)$ 对应 $s=1,t=0$。"},
    7: {"gs": r"令 $x=1$ 得 $f(1,1)=0,f(1,0)=0$。对 $f(x,f(x,x))=x\ln^2x$ 求导代入 $x=1$：$f_1'(1,0)+f_2'(1,0)[f_1'(1,1)+f_2'(1,1)]=0$。对 $f(x^x,x)=x^3\ln x$ 求导代入 $x=1$：$f_1'(1,1)+f_2'(1,1)=1$。故 $f_1'(1,0)+f_2'(1,0)=0$（选 C）。",
       "yc": r"① 代入 $x=1$ 前先求导，顺序错得不出常数关系；② $f(x^x,x)$ 求导漏 $x^x(\ln x+1)$ 因子；③ 误把 $f_1'(1,0)+f_2'(1,0)$ 当 $1$。",
       "jq": r"多重复合偏导，先代 $x=1$ 取特殊点值，再对原式求导代入 $x=1$ 得系数方程；两方程联立消去 $f_1'(1,1)+f_2'(1,1)$。",
       "zy": r"答案 $=0$（非 $\pm1\pm2$）；关键中间量 $f_1'(1,1)+f_2'(1,1)=1$ 来自第二式在 $x=1$。"},
    8: {"gs": r"交换次序：$\int_0^{x^2}\mathrm{d}t\int_{\sqrt t}^x f(t,u)\mathrm{d}u=\int_0^x\mathrm{d}u\int_0^{u^2}f(t,u)\mathrm{d}t$。极限 $=\lim\frac{\int_0^x\mathrm{d}u\int_0^{u^2}f}{x^4}=\lim\frac{\int_0^{x^2}f(t,x)\mathrm{d}t}{4x^3}$。中值 $f(\xi,x)x^2$，可微 $f(\xi,x)=\xi+2x+o(\sqrt{\xi^2+x^2})$，$\xi\le x^2=o(x)\Rightarrow$ 极限 $=\frac{2x}{4x}=\frac12$。",
       "yc": r"① 交换积分次序区域错（应为 $\{(t,u):0\le u\le x,0\le t\le u^2\}$ 非 $0\le t\le x^2$）；② 洛必达后对 $\int_0^x\mathrm{d}u\int_0^{u^2}f$ 求导得 $\int_0^{x^2}f(t,x)\mathrm{d}t$（上限 $x\to$ 被积 $x$ 固定）；③ 漏 $f(\xi,x)\approx\xi+2x$（用 $f_x'=1,f_y'=2$）。",
       "jq": r"二次积分极限先交换次序化“内层简单”，再洛必达 + 积分中值定理，最后用可微线性近似。",
       "zy": r"$f_x'(0,0)=1,f_y'(0,0)=2$ 是近似 $f(\xi,x)\approx\xi+2x$ 的根据；$\xi\in[0,x^2]$ 保证 $\xi=o(x)$。"},
    9: {"gs": r"$f$ 在 $(0,0)$ 不可微。用定义：$\frac{\mathrm{d}z}{\mathrm{d}t}\big|_{t=0}=\lim\frac{2\tan t|\ln(1+t)|}{\sqrt{\tan^2 t+\ln^2(1+t)}\cdot t}=\lim\frac{2|\ln(1+t)|}{\sqrt{\tan^2 t+\ln^2(1+t)}}=\frac{2}{\sqrt2}=\sqrt2$（选 D）。错法：用链导 $f_x'=f_y'=0\Rightarrow0$ 是错误的（不可微不能用链导）。",
       "yc": r"① 误用链导公式（$f$ 在 $(0,0)$ 不可微，$f_x=f_y=0$ 不能代）；② 计算极限时漏绝对值或漏除以 $t$；③ 把 $\sqrt{\tan^2+\ln^2}$ 近似错（$\tan t\sim t,\ln(1+t)\sim t$，比值为 $\sqrt{1+1}=\sqrt2$）。",
       "jq": r"复合函数在内层端点不可微时，回导数定义原式代入；用等价无穷小 $\tan t\sim t$、$\ln(1+t)\sim t$ 化简。",
       "zy": r"本题刻意考“不可微不能用多元链导”；正确答案 $\sqrt2$ 非 $0$。"},
  },
  "好题28-多元函数最值问题": {
    1: {"gs": r"$L=x^2+y^2+\lambda(x^3-xy+y^3-1)$。整理 $(L_x-L_y)$ 得 $(x-y)(x+y+3xy)=0$；$x,y>0$ 时 $x+y+3xy>0\Rightarrow x=y$，代入得 $2x^3-x^2-1=0\Rightarrow x=1,y=1$，$d=\sqrt2$。端点 $x=0\to y=1(d=1)$；$y=0\to x=1(d=1)$。最长 $\sqrt2$，最短 $1$。",
       "yc": r"① $(4)/(5)$ 相除得 $(x-y)(x+y+3xy)=0$ 时，漏 $x+y+3xy>0$ 的讨论直接取 $x=y$；② 只算驻点漏端点（曲线有端点 $x=0$ 或 $y=0$）。",
       "jq": r"约束曲线上最值 $=$ 内部驻点 $+$ 曲线端点都要比；$\lambda$ 不必求，用 $L_x/L_y$ 消去 $\lambda$ 得 $x,y$ 关系。",
       "zy": r"曲线 $x^3-xy+y^3=1$ 在第一象限有端点 $(1,0),(0,1)$；闭曲线段最值需端点比较。"},
    2: {"gs": r"对 $x,y$ 偏导令为 $0$ 得 $x=y=-\frac1z$；代入原方程 $\ln z=\frac2z-2$，单调 $f(z)=\ln z-\frac2z+2$ 唯一解 $z=1$，驻点 $(-1,-1)$。二阶偏导 $A=B=-\frac23,C=0$，$AC-B^2=\frac49>0,A<0\Rightarrow$ 极大值 $z=1$。",
       "yc": r"① 由 $2xz+2=0$ 得 $x=-\frac1z$（不是 $-z/2$）；② $\ln z=\frac2z-2$ 解 $z=1$ 需验证唯一（$f'>0$ 单调）；③ 二阶偏导在驻点处才算（$\partial z/\partial x=\partial z/\partial y=0$ 代入 $(4)(5)(6)$）。",
       "jq": r"隐函数极值先令一阶偏导 $=0$ 解出 $x,y$ 用 $z$ 表，再代回原方程求 $z$；二阶用隐函数再求导，注意只代驻点值。",
       "zy": r"判定充分条件需 $AC-B^2>0$ 且 $A<0$ 为极大；本题 $A=C=-\frac23,B=0$。"},
    3: {"gs": r"$P^2=x^4+2ax^3+(a^2+2b)x^2+2abx+b^2$，积分（奇项消）$=2[\frac15+\frac13(a^2+2b)+b^2]=2f(a,b)$。$f_a=\frac23a=0\Rightarrow a=0$；$f_b=2b+\frac23=0\Rightarrow b=-\frac13$。$A=\frac23,B=0,C=2$，$B^2-AC<0,A>0\Rightarrow$ 最小 $f=\frac4{45}$，故 $\int P^2$ 最小 $\frac8{45}$；$a\to\infty$ 无最大值。",
       "yc": r"① 积分时 $2ax^3,2abx$ 是奇函数在 $[-1,1]$ 上为 $0$，漏消导致错；② 最小值是 $2\times\frac4{45}=\frac8{45}$ 非 $\frac4{45}$；③ 问“是否有最大”答无（$a\to\infty$ 发散）。",
       "jq": r"含参数积分最值 $=$ 用对称性消奇次项 $\to$ 二元函数极值；闭区域无界则无最大值。",
       "zy": r"$P(x)=x^2+ax+b$ 是二次多项式，积分最值只有最小值（无最大值）。"},
    4: {"gs": r"$f=x^2+y^2$，约束 $(x-1)^3=y^2\ge0\Rightarrow x\ge1$。Lagrange 方程组无解（尖点 $(1,0)$ 不可微）。由几何：点 $(1,0)$ 取最小 $1$；曲线趋于无穷无最大（选 D：无最大，有最小）。",
       "yc": r"① 见 Lagrange 无解就乱选（实际约束曲线有尖点 $(1,0)$ 不可微，乘数法失效）；② 误认为无解 $=$ 无最值；③ 漏 $x\ge1$ 的几何信息。",
       "jq": r"约束含不可微尖点，乘数法失效时回到几何/定义；比较尖点处值与趋势。",
       "zy": r"$(1,0)$ 是曲线尖点（$y^2=(x-1)^3$ 在 $x=1$ 导数不存在），必须单独考虑；选 D。"},
    5: {"gs": r"$u_{xx}=2\Rightarrow u_x=2x$（$u_x(0,y,z)=0$）；$u_y=2y\Rightarrow u=x^2+y^2+C(z)$；$u(0,0,z)=z^2\Rightarrow C(z)=z^2$，故 $u=x^2+y^2+z^2$。约束 $z=x^2+y^2$ 与 $x+2y+z=10$，Lagrange 得驻点 $(1,2,5),(-2,-4,20)$，$u$ 最小 $30$、最大 $420$。",
       "yc": r"① 由 $u_{xx}=2$ 积 $u_x=2x+c(y,z)$，用 $u_x(0,y,z)=0$ 定 $c=0$（漏 $c$ 含 $y,z$）；② $u(0,0,z)=z^2$ 定 $C(z)$ 而非常数；③ 两约束 Lagrange 解驻点需联立 $z=x^2+y^2$ 与 $x+2y+z=10$。",
       "jq": r"偏微分方程反求 $u$ 用累次积分 $+$ 初值定函数；双约束最值直接 Lagrange 五变量。",
       "zy": r"$u=x^2+y^2+z^2$ 是到点距离平方；驻点 $(1,2,5)\to30$，$(-2,-4,20)\to420$，闭曲线段（两曲面交）最值即此。"},
    6: {"gs": r"$\frac{\partial z}{\partial x}=\frac{2x-2}{1+\mathrm{e}^z}$，$\frac{\partial z}{\partial y}=\frac{2y}{1+\mathrm{e}^z}$，区域内驻点 $(1,0)$。边界 $x^2+2y^2=4$：$L=z+\lambda(x^2+2y^2-4)$，由 $L_y$ 得 $y=0\Rightarrow x=\pm2$，驻点 $(2,0),(-2,0)$。比较：$\mathrm{e}^z+z=1$ 于 $(1,0)$，$=2$ 于 $(2,0)$，$=10$ 于 $(-2,0)$；$g(z)=\mathrm{e}^z+z$ 单增 $\Rightarrow$ 最小 $(1,0)$、最大 $(-2,0)$。",
       "yc": r"① 隐函数偏导 $\partial z/\partial x$ 漏 $(1+\mathrm{e}^z)$ 分母（应是 $\frac{2x-2}{1+\mathrm{e}^z}$）；② 边界只算 $y=0$ 漏讨论；③ 比较 $z$ 值靠 $\mathrm{e}^z+z$ 单调性，别直接算 $z$ 数值。",
       "jq": r"隐函数区域最值 $=$ 内部驻点 $+$ 边界（乘数法）驻点；边界代入原隐式方程得 $\mathrm{e}^z+z=$ 常数，用单调性比大小。",
       "zy": r"区域包含边界，闭区域必有最值；最小值点 $(1,0)$、最大值点 $(-2,0)$。"},
    7: {"gs": r"$y'=-\frac{3x+y}{x+3y}$。切线截距 $X_{\text{截}}=x+\frac{y(x+3y)}{3x+y}=\frac{a}{3x+y}$，$Y_{\text{截}}=\frac{a}{x+3y}$（用 $3x^2+2xy+3y^2=a$）。$S=\frac{a^2}{2(3x+y)(x+3y)}=\frac{a^2}{2(a+8xy)}$。$xy$ 最大时 $S$ 最小；$L=xy+\lambda(3x^2+2xy+3y^2-a)\Rightarrow x=y=\frac{\sqrt{2a}}{4}$，$S_{\min}=\frac{a}{4}=\frac14\Rightarrow a=1$。",
       "yc": r"① 截距公式化简错（分子应 $3x^2+2xy+3y^2=a$）；② $S=\frac{a^2}{2(a+8xy)}$ 中“$xy$ 最大 $S$ 最小”方向别反；③ $x=y$ 由对称性/Lagrange 得，代入 $xy=\frac{a}{8}$。",
       "jq": r"切线三角形面积用截距公式；$S$ 表成 $\frac{a^2}{2(a+8xy)}$ 后转为求 $xy$ 在椭圆约束下最大。",
       "zy": r"第一象限 $x,y>0$；结果 $a=1$（$S_{\min}=a/4$ 令 $=\frac14$）。"},
    8: {"gs": r"$x^{2/3}+y^{2/3}=1$，$y'=-(\frac{y}{x})^{1/3}$。切线截距 $X_{\text{截}}=x_0^{1/3}$（用 $x_0^{2/3}+y_0^{2/3}=1$），$Y_{\text{截}}=y_0^{1/3}$，故 $l=x_0^{1/3}+y_0^{1/3}$。约束 $x^{2/3}+y^{2/3}=1$ 下 $F=x^{1/3}+y^{1/3}+\lambda(x^{2/3}+y^{2/3}-1)$，得 $x=y=2^{-3/2}$，$l_{\max}=\sqrt2$。",
       "yc": r"① 截距算错：应为 $x_0^{1/3}$ 与 $y_0^{1/3}$（不是 $x_0,y_0$）；② $l=x^{1/3}+y^{1/3}$ 在 $x^{2/3}+y^{2/3}=1$ 下，误用普通 Lagrange 把指数搞混；③ 由 $F_x,F_y$ 得 $x=y$ 别漏。",
       "jq": r"星形线切线截距恰为 $x^{1/3},y^{1/3}$（经典结论）；目标 $l$ 与约束同形，Lagrange 直接。",
       "zy": r"截距式利用 $x_0^{2/3}+y_0^{2/3}=1$ 化简；最大值 $\sqrt2$（唯一驻点 $+$ 实际意义）。"},
    9: {"gs": r"（Ⅰ）$f_x=3(x-y)^2\Rightarrow f=(x-y)^3+C(y)$；$f_y=-3(x-y)^2+C'(y)=-3(x^2-2xy+2y^2-2)\Rightarrow C'(y)=6-3y^2\Rightarrow C(y)=6y-y^3$，$f=(x-y)^3-y^3+6y$（$f(0,0)=0$）。（Ⅱ）区域 $D:x\ge0,y\ge0,x+y\le3$；驻点 $(\sqrt2,\sqrt2)\to4\sqrt2$；边界 $L_1:x=0\to(0,1):4$；$L_3:y=3-x\to(\frac53,\frac43):\frac{17}{3}$；交点 $(3,0):27$（最大），$(0,3):-36$（最小）。",
       "yc": r"① 由 $f_x$ 积 $f=(x-y)^3+C(y)$，$C'(y)$ 符号错（应用 $f_y$ 等式反解）；② 闭区域最值漏边界 $L_1/L_2/L_3$ 或交点；③ $f(3,0)=27,f(0,3)=-36$ 别反。",
       "jq": r"全微分反求 $f$ 先对 $x$ 积 $+C(y)$ 再比对 $f_y$；闭区域最值 $=$ 驻点 $+$ 三条边界 $+$ 三顶点比较。",
       "zy": r"$f$ 无常数项（$f(0,0)=0$）；最值 $27$ 与 $-36$ 在边界顶点取得，非驻点。"},
  },
  "好题29-二重积分": {
    1: {"gs": r"$D$ 顶点 $(1,1),(-1,1),(-1,-1)$，面积 $2$。令 $A=\iint_D f$，则 $f=xy+A$；积分 $A=\iint xy+2A$。作 $y=-x$ 辅助线：$D$ 分块关于轴对面积分 $xy$ 为奇 $\to\iint xy=0$，故 $A=2A\Rightarrow A=0$，$f=xy$，$f(y,x)=f(x,y)$（选 C）。",
       "yc": r"① 面积 $S_D=2$（三角形底 $2$ 高 $2$ 除以 $2$）非 $1$；② 漏 $\iint_D A\,\mathrm{d}\sigma=A\cdot S_D=2A$；③ $A=0$ 后 $f=xy$，C/D 等右端 $\iint_{D_1}xy>0$ 非零故错。",
       "jq": r"含 $\iint_D f$ 的积分方程令 $A=\iint f$，两边积分化 $A$ 的一元方程；对称性消 $\iint xy$。",
       "zy": r"$D$ 不以坐标轴为对称轴，但以 $y=-x$ 分块可证 $xy$ 积分为 $0$；结论 $f(x,y)=xy$ 对称故 $f(y,x)=f$。"},
    2: {"gs": r"曲线关于 $y$ 轴对称；$x\ge0$ 时 $y=\frac{1-x}{1+x}$。$\iint_D x\,\mathrm{d}\sigma=0$（对称）。$I=\iint[2\ln(1+y)-y]\mathrm{d}\sigma=2\iint_{D_1}[\cdots]$；先 $x$ 积分 $x=\frac{1-y}{1+y}$，注意 $[2\ln(1+y)-y]'=\frac{1-y}{1+y}$，故 $I=[2\ln(1+y)-y]^2\big|_0^1=(2\ln2-1)^2$。",
       "yc": r"① 漏对称性 $\iint x=0$ 直接算；② 先 $x$ 积分上限 $x=\frac{1-y}{1+y}$ 由 $xy+x+y=1$ 解错；③ 关键是认出 $[2\ln(1+y)-y]'=\frac{1-y}{1+y}$ 才能凑微分。",
       "jq": r"对称区域先消奇次项（$\iint x=0$）；被积函数导数恰为 $x$ 的积分上限 $\to$ 凑微分平方。",
       "zy": r"结果 $(2\ln2-1)^2$ 非 $2\ln2-1$；$D$ 第一象限部分 $D_1$ 积分乘 $2$."},
    3: {"gs": r"交换次序（$t\le x^2$ 时 $\sqrt t\le x$，上限小）得 $\int_0^{x^2}\mathrm{d}t\int_x^{\sqrt t}f=-\int_0^x\mathrm{d}u\int_0^{u^2}f(t,u)\mathrm{d}t$。$1-\mathrm{e}^{-x^4/4}\sim\frac{x^4}{4}$；原式 $=\lim\frac{-\int_0^{x^2}f(t,x)\mathrm{d}t}{x^3}$。中值 $f(\xi,x)x^2$，可微 $f(\xi,x)=\xi+x+o(x)$（$f_y'(0,0)=1$）$\to$ 极限 $=-1$。",
       "yc": r"① 交换次序符号（原 $\int_x^{\sqrt t}$ 上小下大，交换带负号）易漏；② $1-\mathrm{e}^{-x^4/4}\sim\frac{x^4}{4}$ 别写成 $x^4$；③ 近似 $f(\xi,x)=f_y'(0,0)x+o(x)=x+o(x)$（$f_x'$ 项 $\xi/x\to0$）。",
       "jq": r"积分上限含 $x^2$ 的极限，交换次序后洛必达 $+$ 中值定理；可微性给线性近似 $f\approx f_x'\xi+f_y'x$。",
       "zy": r"本题 $f_y'(0,0)=1$ 是关键；结果 $-1$（负号来自交换次序的 $-\int$）。"},
    4: {"gs": r"$I=\int_0^{2\pi}\mathrm{d}\theta\int_{\theta/2}^\pi\theta^2\mathrm{e}^{r^2}\mathrm{d}r$，区域 $0\le\theta\le2\pi,\frac{\theta}{2}\le r\le\pi$ 即 $0\le r\le\pi,0\le\theta\le2r$。交换：$I=\int_0^\pi\mathrm{d}r\int_0^{2r}\theta^2\mathrm{e}^{r^2}\mathrm{d}\theta=\int_0^\pi\mathrm{e}^{r^2}\cdot\frac{8}{3}r^3\,\mathrm{d}r=\frac43\int_0^{\pi^2}t\mathrm{e}^t\mathrm{d}t=\frac43\mathrm{e}^{\pi^2}(\pi^2-1)+\frac43$。",
       "yc": r"① 交换后 $\theta$ 范围 $0\le\theta\le2r$（不是 $0\le2r\le\theta$）；② $\int_0^{2r}\theta^2\mathrm{d}\theta=\frac{(2r)^3}{3}=\frac{8r^3}{3}$ 别漏 $8$；③ $r^2=t$ 后 $\mathrm{d}r$ 转 $\mathrm{d}t$：$r^3\mathrm{d}r=\frac12t\,\mathrm{d}t$。",
       "jq": r"极坐标累次积分交换次序先画 $r-\theta$ 区域（$r$ 从 $\theta/2$ 到 $\pi$）；换元 $r^2=t$ 简化 $\mathrm{e}^{r^2}$。",
       "zy": r"结果 $\frac43\mathrm{e}^{\pi^2}(\pi^2-1)+\frac43$；$\theta$ 是角度但被积含 $\theta^2$，交换后照积。"},
    5: {"gs": r"$D:0\le y\le1-x,0\le x\le1$（直角三角）。极坐标 $r=\frac{1}{\cos\theta+\sin\theta}$。$I=\int_0^{\pi/2}\mathrm{d}\theta\int_0^{1/(\cos\theta+\sin\theta)}\mathrm{e}^{\frac{\cos\theta}{\cos\theta+\sin\theta}}r\,\mathrm{d}r=\frac12\int\mathrm{e}^{\frac{\cos}{\cos+\sin}}\frac{1}{(\cos+\sin)^2}\mathrm{d}\theta=-\frac12\mathrm{e}^{\frac{\cos}{\cos+\sin}}\big|_0^{\pi/2}=\frac12(\mathrm{e}-1)$。",
       "yc": r"① 斜边 $x+y=1$ 极坐标 $r=\frac{1}{\cos\theta+\sin\theta}$ 写错（应为 $1$ 非别的）；② 积分 $-\frac12\mathrm{e}^{u}\big|$ 上下限 $u(\pi/2)=0,u(0)=1\to-\frac12(1-\mathrm{e})=\frac12(\mathrm{e}-1)$ 别反；③ 漏 $\frac12$（$r\,\mathrm{d}r$ 积分得 $r^2/2$）。",
       "jq": r"被积 $\mathrm{e}^{x/(x+y)}$ 在极坐标下与 $\theta$ 相关但 $r$ 分离，先积 $r$ 得 $r^2/2$，再凑 $\mathrm{d}[\frac{\cos}{\cos+\sin}]$。",
       "zy": r"结果 $\frac12(\mathrm{e}-1)$；$u=\frac{\cos\theta}{\cos\theta+\sin\theta}$，$\frac{\mathrm{d}u}{\mathrm{d}\theta}=-\frac{1}{(\cos+\sin)^2}$."},
    6: {"gs": r"$D:x+y\le1,x,y\ge0$。法一：令 $x+y=u,x=uv\Rightarrow J=u$，$\sqrt{xy}=u\sqrt{v(1-v)}$，$I=\int_0^1\mathrm{e}^{-u}\mathrm{d}u\cdot\int_0^1\frac{\mathrm{d}v}{\sqrt{v(1-v)}}=(1-\mathrm{e}^{-1})\cdot\pi$。$\int_0^1\frac{\mathrm{d}v}{\sqrt{v(1-v)}}=\arcsin(2v-1)\big|_0^1=\pi$。法二：换元 $u=-(x+y),v=x$ 同样得 $\pi(1-\frac1{\mathrm{e}})$。",
       "yc": r"① 法一雅可比 $|J|=u$ 易漏（或直接当 $1$）；② $\int_0^1\frac{\mathrm{d}v}{\sqrt{v(1-v)}}=\pi$ 经典积分（Beta 或 $\arcsin$）别算成 $2$；③ 法二区域 $D'$ 边界 $-1\le u+v\le0$ 易错。",
       "jq": r"被积含 $\sqrt{xy}$ 且区域 $x+y\le1$，用 $u=x+y,v=x/(x+y)$（或 $x=uv$）分离；$\int\frac{\mathrm{d}v}{\sqrt{v(1-v)}}=\pi$ 是必记结论。",
       "zy": r"结果 $\pi(1-\frac1{\mathrm{e}})$；两法等价，法一更直。"},
    7: {"gs": r"$L:y=\cos x$，切线 $L_1:y=x+\frac{\pi}{2}$（点 $(-\frac{\pi}{2},0)$ 处 $y'=1$），$L_2:y=-x+\frac{\pi}{2}$（点 $(\frac{\pi}{2},0)$ 处 $y'=-1$）。区域 $D$ 上边界两切线交于 $(0,\frac{\pi}{2})$，下边界 $y=\cos x$。①错（上限恒 $\frac{\pi}{2}$ 对应更大区域）；②错（对应三角形含曲线下）；③错（暗示 $f$ 对称且 $x$ 下限只覆盖右半）；④对（按 $x$ 剖分）：左段 $\int_{\cos x}^{x+\pi/2}$，右段 $\int_{\cos x}^{\pi/2-x}$（选 A，仅 $1$ 个对）。",
       "yc": r"① 切线方程在 $(-\frac{\pi}{2},0)$：$y'=-\sin(-\frac{\pi}{2})=1\Rightarrow y=x+\frac{\pi}{2}$（不是 $-x$）；② 误以为③对（③乘 $2$ 假设 $f$ 关于 $y$ 轴对称，一般 $f$ 不成立）；③ ④的左右段上界分别是 $x+\frac{\pi}{2}$ 与 $\frac{\pi}{2}-x$ 别混。",
       "jq": r"累次积分表示先画区域图定上下边界；分段按 $x=0$ 剖（两切线交点 $x=0$），上界分别为两切线。",
       "zy": r"仅④成立（选 A $1$ 个）；①上限恒 $\frac{\pi}{2}$ 错，②对应三角形错，③对称性假设错。"},
    8: {"gs": r"$D:0\le y\le\sqrt{2x-x^2}$（圆心 $(1,0)$ 半径 $1$ 上半圆盘，$S_D=\frac{\pi}{2}$）。令 $A=\iint_D f$，$f=\frac{1}{\sqrt{|x^2+y^2-2|+2}}+\frac{A}{\pi}$；积分 $A=2\iint_D\frac{1}{\sqrt{|r^2-2|+2}}\mathrm{d}\sigma$（因 $\frac{A}{\pi}\cdot\frac{\pi}{2}=\frac{A}{2}\Rightarrow A=\cdots+\frac{A}{2}$）。圆 $r=\sqrt2$ 分 $D$ 为 $D_1(r\le\sqrt2)$ 与 $D_2(r\ge\sqrt2)$：$D_1$ 被积 $\frac{1}{\sqrt{4-r^2}}$，$D_2$ 被积 $\frac{1}{r}$。极坐标 $r=2\cos\theta,0\le\theta\le\frac{\pi}{2}$；$r=\sqrt2$ 交 $\theta=\frac{\pi}{4}$。$A=(2-\sqrt2)\pi$。",
       "yc": r"① $D$ 面积 $S_D=\frac{\pi}{2}$（半圆）非 $\pi$；② 由 $A=\iint\cdots+\frac{A}{\pi}\cdot\frac{\pi}{2}$ 得 $A=2\iint\cdots$（移项 $A-\frac{A}{2}=\iint$）；③ 分段：$r\le\sqrt2$ 时 $|r^2-2|+2=4-r^2$，$r\ge\sqrt2$ 时为 $r^2$；④ 积分三项相加易算错（复核得 $(2-\sqrt2)\pi$）。",
       "jq": r"含 $\iint_D f$ 常数 $A$ 的方程令 $A$ 再积分；绝对值由圆 $r=\sqrt2$ 分界成两块不同被积；极坐标 $r=2\cos\theta$。",
       "zy": r"结果 $(2-\sqrt2)\pi$；$r=\sqrt2$ 与 $r=2\cos\theta$ 交 $\theta=\frac{\pi}{4}$ 是分块界；三项求和需仔细。"},
  },
}
